//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServicioTransporte {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Servicios/", ConfigurationName="ServicioTransporte.ServicioTransporte")]
    public interface ServicioTransporte {
        
        // CODEGEN: El parámetro 'v_ID_TRANSPORTE' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioTransporte/actualizarTransporteRequest", ReplyAction="http://Servicios/ServicioTransporte/actualizarTransporteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUI.ServicioTransporte.actualizarTransporteResponse actualizarTransporte(CapaGUI.ServicioTransporte.actualizarTransporteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioTransporte/actualizarTransporteRequest", ReplyAction="http://Servicios/ServicioTransporte/actualizarTransporteResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioTransporte.actualizarTransporteResponse> actualizarTransporteAsync(CapaGUI.ServicioTransporte.actualizarTransporteRequest request);
        
        // CODEGEN: El parámetro 'idTransporte' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioTransporte/insertReservaServiceRequest", ReplyAction="http://Servicios/ServicioTransporte/insertReservaServiceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUI.ServicioTransporte.insertReservaServiceResponse insertReservaService(CapaGUI.ServicioTransporte.insertReservaServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioTransporte/insertReservaServiceRequest", ReplyAction="http://Servicios/ServicioTransporte/insertReservaServiceResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioTransporte.insertReservaServiceResponse> insertReservaServiceAsync(CapaGUI.ServicioTransporte.insertReservaServiceRequest request);
        
        // CODEGEN: El parámetro 'Precio' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioTransporte/IngresoTransporteRequest", ReplyAction="http://Servicios/ServicioTransporte/IngresoTransporteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUI.ServicioTransporte.IngresoTransporteResponse IngresoTransporte(CapaGUI.ServicioTransporte.IngresoTransporteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioTransporte/IngresoTransporteRequest", ReplyAction="http://Servicios/ServicioTransporte/IngresoTransporteResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioTransporte.IngresoTransporteResponse> IngresoTransporteAsync(CapaGUI.ServicioTransporte.IngresoTransporteRequest request);
        
        // CODEGEN: El parámetro 'idTransporte' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioTransporte/eliminarTransporteRequest", ReplyAction="http://Servicios/ServicioTransporte/eliminarTransporteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUI.ServicioTransporte.eliminarTransporteResponse eliminarTransporte(CapaGUI.ServicioTransporte.eliminarTransporteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioTransporte/eliminarTransporteRequest", ReplyAction="http://Servicios/ServicioTransporte/eliminarTransporteResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioTransporte.eliminarTransporteResponse> eliminarTransporteAsync(CapaGUI.ServicioTransporte.eliminarTransporteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioTransporte/listarTransporteRequest", ReplyAction="http://Servicios/ServicioTransporte/listarTransporteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaGUI.ServicioTransporte.listarTransporteResponse listarTransporte(CapaGUI.ServicioTransporte.listarTransporteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioTransporte/listarTransporteRequest", ReplyAction="http://Servicios/ServicioTransporte/listarTransporteResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioTransporte.listarTransporteResponse> listarTransporteAsync(CapaGUI.ServicioTransporte.listarTransporteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarTransporte", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class actualizarTransporteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int v_ID_TRANSPORTE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int v_PRECIO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int v_ID_DISPONIBILIDAD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int v_CAPACIDAD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string V_DESCRIPCION;
        
        public actualizarTransporteRequest() {
        }
        
        public actualizarTransporteRequest(int v_ID_TRANSPORTE, int v_PRECIO, int v_ID_DISPONIBILIDAD, int v_CAPACIDAD, string V_DESCRIPCION) {
            this.v_ID_TRANSPORTE = v_ID_TRANSPORTE;
            this.v_PRECIO = v_PRECIO;
            this.v_ID_DISPONIBILIDAD = v_ID_DISPONIBILIDAD;
            this.v_CAPACIDAD = v_CAPACIDAD;
            this.V_DESCRIPCION = V_DESCRIPCION;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarTransporteResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class actualizarTransporteResponse {
        
        public actualizarTransporteResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertReservaService", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class insertReservaServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTransporte;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string horario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idReserva;
        
        public insertReservaServiceRequest() {
        }
        
        public insertReservaServiceRequest(int idTransporte, string direccion, string horario, int idReserva) {
            this.idTransporte = idTransporte;
            this.direccion = direccion;
            this.horario = horario;
            this.idReserva = idReserva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertReservaServiceResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class insertReservaServiceResponse {
        
        public insertReservaServiceResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IngresoTransporte", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class IngresoTransporteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Precio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Disponbilidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int V_CAPACIDAD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string V_DESCRIPCION;
        
        public IngresoTransporteRequest() {
        }
        
        public IngresoTransporteRequest(int Precio, int Disponbilidad, int V_CAPACIDAD, string V_DESCRIPCION) {
            this.Precio = Precio;
            this.Disponbilidad = Disponbilidad;
            this.V_CAPACIDAD = V_CAPACIDAD;
            this.V_DESCRIPCION = V_DESCRIPCION;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IngresoTransporteResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class IngresoTransporteResponse {
        
        public IngresoTransporteResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarTransporte", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class eliminarTransporteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTransporte;
        
        public eliminarTransporteRequest() {
        }
        
        public eliminarTransporteRequest(int idTransporte) {
            this.idTransporte = idTransporte;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarTransporteResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class eliminarTransporteResponse {
        
        public eliminarTransporteResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class listaTransporte : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int capacidadField;
        
        private string descripcionField;
        
        private string disponibilidadField;
        
        private int idTransporteField;
        
        private int precioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int capacidad {
            get {
                return this.capacidadField;
            }
            set {
                this.capacidadField = value;
                this.RaisePropertyChanged("capacidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string disponibilidad {
            get {
                return this.disponibilidadField;
            }
            set {
                this.disponibilidadField = value;
                this.RaisePropertyChanged("disponibilidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idTransporte {
            get {
                return this.idTransporteField;
            }
            set {
                this.idTransporteField = value;
                this.RaisePropertyChanged("idTransporte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTransporte", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class listarTransporteRequest {
        
        public listarTransporteRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTransporteResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class listarTransporteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CapaGUI.ServicioTransporte.listaTransporte[] @return;
        
        public listarTransporteResponse() {
        }
        
        public listarTransporteResponse(CapaGUI.ServicioTransporte.listaTransporte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioTransporteChannel : CapaGUI.ServicioTransporte.ServicioTransporte, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioTransporteClient : System.ServiceModel.ClientBase<CapaGUI.ServicioTransporte.ServicioTransporte>, CapaGUI.ServicioTransporte.ServicioTransporte {
        
        public ServicioTransporteClient() {
        }
        
        public ServicioTransporteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioTransporteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioTransporteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioTransporteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioTransporte.actualizarTransporteResponse CapaGUI.ServicioTransporte.ServicioTransporte.actualizarTransporte(CapaGUI.ServicioTransporte.actualizarTransporteRequest request) {
            return base.Channel.actualizarTransporte(request);
        }
        
        public void actualizarTransporte(int v_ID_TRANSPORTE, int v_PRECIO, int v_ID_DISPONIBILIDAD, int v_CAPACIDAD, string V_DESCRIPCION) {
            CapaGUI.ServicioTransporte.actualizarTransporteRequest inValue = new CapaGUI.ServicioTransporte.actualizarTransporteRequest();
            inValue.v_ID_TRANSPORTE = v_ID_TRANSPORTE;
            inValue.v_PRECIO = v_PRECIO;
            inValue.v_ID_DISPONIBILIDAD = v_ID_DISPONIBILIDAD;
            inValue.v_CAPACIDAD = v_CAPACIDAD;
            inValue.V_DESCRIPCION = V_DESCRIPCION;
            CapaGUI.ServicioTransporte.actualizarTransporteResponse retVal = ((CapaGUI.ServicioTransporte.ServicioTransporte)(this)).actualizarTransporte(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioTransporte.actualizarTransporteResponse> CapaGUI.ServicioTransporte.ServicioTransporte.actualizarTransporteAsync(CapaGUI.ServicioTransporte.actualizarTransporteRequest request) {
            return base.Channel.actualizarTransporteAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioTransporte.actualizarTransporteResponse> actualizarTransporteAsync(int v_ID_TRANSPORTE, int v_PRECIO, int v_ID_DISPONIBILIDAD, int v_CAPACIDAD, string V_DESCRIPCION) {
            CapaGUI.ServicioTransporte.actualizarTransporteRequest inValue = new CapaGUI.ServicioTransporte.actualizarTransporteRequest();
            inValue.v_ID_TRANSPORTE = v_ID_TRANSPORTE;
            inValue.v_PRECIO = v_PRECIO;
            inValue.v_ID_DISPONIBILIDAD = v_ID_DISPONIBILIDAD;
            inValue.v_CAPACIDAD = v_CAPACIDAD;
            inValue.V_DESCRIPCION = V_DESCRIPCION;
            return ((CapaGUI.ServicioTransporte.ServicioTransporte)(this)).actualizarTransporteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioTransporte.insertReservaServiceResponse CapaGUI.ServicioTransporte.ServicioTransporte.insertReservaService(CapaGUI.ServicioTransporte.insertReservaServiceRequest request) {
            return base.Channel.insertReservaService(request);
        }
        
        public void insertReservaService(int idTransporte, string direccion, string horario, int idReserva) {
            CapaGUI.ServicioTransporte.insertReservaServiceRequest inValue = new CapaGUI.ServicioTransporte.insertReservaServiceRequest();
            inValue.idTransporte = idTransporte;
            inValue.direccion = direccion;
            inValue.horario = horario;
            inValue.idReserva = idReserva;
            CapaGUI.ServicioTransporte.insertReservaServiceResponse retVal = ((CapaGUI.ServicioTransporte.ServicioTransporte)(this)).insertReservaService(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioTransporte.insertReservaServiceResponse> CapaGUI.ServicioTransporte.ServicioTransporte.insertReservaServiceAsync(CapaGUI.ServicioTransporte.insertReservaServiceRequest request) {
            return base.Channel.insertReservaServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioTransporte.insertReservaServiceResponse> insertReservaServiceAsync(int idTransporte, string direccion, string horario, int idReserva) {
            CapaGUI.ServicioTransporte.insertReservaServiceRequest inValue = new CapaGUI.ServicioTransporte.insertReservaServiceRequest();
            inValue.idTransporte = idTransporte;
            inValue.direccion = direccion;
            inValue.horario = horario;
            inValue.idReserva = idReserva;
            return ((CapaGUI.ServicioTransporte.ServicioTransporte)(this)).insertReservaServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioTransporte.IngresoTransporteResponse CapaGUI.ServicioTransporte.ServicioTransporte.IngresoTransporte(CapaGUI.ServicioTransporte.IngresoTransporteRequest request) {
            return base.Channel.IngresoTransporte(request);
        }
        
        public void IngresoTransporte(int Precio, int Disponbilidad, int V_CAPACIDAD, string V_DESCRIPCION) {
            CapaGUI.ServicioTransporte.IngresoTransporteRequest inValue = new CapaGUI.ServicioTransporte.IngresoTransporteRequest();
            inValue.Precio = Precio;
            inValue.Disponbilidad = Disponbilidad;
            inValue.V_CAPACIDAD = V_CAPACIDAD;
            inValue.V_DESCRIPCION = V_DESCRIPCION;
            CapaGUI.ServicioTransporte.IngresoTransporteResponse retVal = ((CapaGUI.ServicioTransporte.ServicioTransporte)(this)).IngresoTransporte(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioTransporte.IngresoTransporteResponse> CapaGUI.ServicioTransporte.ServicioTransporte.IngresoTransporteAsync(CapaGUI.ServicioTransporte.IngresoTransporteRequest request) {
            return base.Channel.IngresoTransporteAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioTransporte.IngresoTransporteResponse> IngresoTransporteAsync(int Precio, int Disponbilidad, int V_CAPACIDAD, string V_DESCRIPCION) {
            CapaGUI.ServicioTransporte.IngresoTransporteRequest inValue = new CapaGUI.ServicioTransporte.IngresoTransporteRequest();
            inValue.Precio = Precio;
            inValue.Disponbilidad = Disponbilidad;
            inValue.V_CAPACIDAD = V_CAPACIDAD;
            inValue.V_DESCRIPCION = V_DESCRIPCION;
            return ((CapaGUI.ServicioTransporte.ServicioTransporte)(this)).IngresoTransporteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioTransporte.eliminarTransporteResponse CapaGUI.ServicioTransporte.ServicioTransporte.eliminarTransporte(CapaGUI.ServicioTransporte.eliminarTransporteRequest request) {
            return base.Channel.eliminarTransporte(request);
        }
        
        public void eliminarTransporte(int idTransporte) {
            CapaGUI.ServicioTransporte.eliminarTransporteRequest inValue = new CapaGUI.ServicioTransporte.eliminarTransporteRequest();
            inValue.idTransporte = idTransporte;
            CapaGUI.ServicioTransporte.eliminarTransporteResponse retVal = ((CapaGUI.ServicioTransporte.ServicioTransporte)(this)).eliminarTransporte(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioTransporte.eliminarTransporteResponse> CapaGUI.ServicioTransporte.ServicioTransporte.eliminarTransporteAsync(CapaGUI.ServicioTransporte.eliminarTransporteRequest request) {
            return base.Channel.eliminarTransporteAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioTransporte.eliminarTransporteResponse> eliminarTransporteAsync(int idTransporte) {
            CapaGUI.ServicioTransporte.eliminarTransporteRequest inValue = new CapaGUI.ServicioTransporte.eliminarTransporteRequest();
            inValue.idTransporte = idTransporte;
            return ((CapaGUI.ServicioTransporte.ServicioTransporte)(this)).eliminarTransporteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioTransporte.listarTransporteResponse CapaGUI.ServicioTransporte.ServicioTransporte.listarTransporte(CapaGUI.ServicioTransporte.listarTransporteRequest request) {
            return base.Channel.listarTransporte(request);
        }
        
        public CapaGUI.ServicioTransporte.listaTransporte[] listarTransporte() {
            CapaGUI.ServicioTransporte.listarTransporteRequest inValue = new CapaGUI.ServicioTransporte.listarTransporteRequest();
            CapaGUI.ServicioTransporte.listarTransporteResponse retVal = ((CapaGUI.ServicioTransporte.ServicioTransporte)(this)).listarTransporte(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioTransporte.listarTransporteResponse> CapaGUI.ServicioTransporte.ServicioTransporte.listarTransporteAsync(CapaGUI.ServicioTransporte.listarTransporteRequest request) {
            return base.Channel.listarTransporteAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioTransporte.listarTransporteResponse> listarTransporteAsync() {
            CapaGUI.ServicioTransporte.listarTransporteRequest inValue = new CapaGUI.ServicioTransporte.listarTransporteRequest();
            return ((CapaGUI.ServicioTransporte.ServicioTransporte)(this)).listarTransporteAsync(inValue);
        }
    }
}
