//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServicioServicioTurismo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Servicios/", ConfigurationName="ServicioServicioTurismo.ServicioServicioTurismo")]
    public interface ServicioServicioTurismo {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://Servicios/).
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioServicioTurismo/insertServiceTurismoRequest", ReplyAction="http://Servicios/ServicioServicioTurismo/insertServiceTurismoResponse")]
        CapaGUI.ServicioServicioTurismo.insertServiceTurismoResponse insertServiceTurismo(CapaGUI.ServicioServicioTurismo.insertServiceTurismoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioServicioTurismo/insertServiceTurismoRequest", ReplyAction="http://Servicios/ServicioServicioTurismo/insertServiceTurismoResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioServicioTurismo.insertServiceTurismoResponse> insertServiceTurismoAsync(CapaGUI.ServicioServicioTurismo.insertServiceTurismoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertServiceTurismo", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class insertServiceTurismoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int idTurismo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int idReserva;
        
        public insertServiceTurismoRequest() {
        }
        
        public insertServiceTurismoRequest(int idTurismo, int idReserva) {
            this.idTurismo = idTurismo;
            this.idReserva = idReserva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertServiceTurismoResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class insertServiceTurismoResponse {
        
        public insertServiceTurismoResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioServicioTurismoChannel : CapaGUI.ServicioServicioTurismo.ServicioServicioTurismo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioServicioTurismoClient : System.ServiceModel.ClientBase<CapaGUI.ServicioServicioTurismo.ServicioServicioTurismo>, CapaGUI.ServicioServicioTurismo.ServicioServicioTurismo {
        
        public ServicioServicioTurismoClient() {
        }
        
        public ServicioServicioTurismoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioServicioTurismoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioServicioTurismoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioServicioTurismoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioServicioTurismo.insertServiceTurismoResponse CapaGUI.ServicioServicioTurismo.ServicioServicioTurismo.insertServiceTurismo(CapaGUI.ServicioServicioTurismo.insertServiceTurismoRequest request) {
            return base.Channel.insertServiceTurismo(request);
        }
        
        public void insertServiceTurismo(int idTurismo, int idReserva) {
            CapaGUI.ServicioServicioTurismo.insertServiceTurismoRequest inValue = new CapaGUI.ServicioServicioTurismo.insertServiceTurismoRequest();
            inValue.idTurismo = idTurismo;
            inValue.idReserva = idReserva;
            CapaGUI.ServicioServicioTurismo.insertServiceTurismoResponse retVal = ((CapaGUI.ServicioServicioTurismo.ServicioServicioTurismo)(this)).insertServiceTurismo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioServicioTurismo.insertServiceTurismoResponse> CapaGUI.ServicioServicioTurismo.ServicioServicioTurismo.insertServiceTurismoAsync(CapaGUI.ServicioServicioTurismo.insertServiceTurismoRequest request) {
            return base.Channel.insertServiceTurismoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioServicioTurismo.insertServiceTurismoResponse> insertServiceTurismoAsync(int idTurismo, int idReserva) {
            CapaGUI.ServicioServicioTurismo.insertServiceTurismoRequest inValue = new CapaGUI.ServicioServicioTurismo.insertServiceTurismoRequest();
            inValue.idTurismo = idTurismo;
            inValue.idReserva = idReserva;
            return ((CapaGUI.ServicioServicioTurismo.ServicioServicioTurismo)(this)).insertServiceTurismoAsync(inValue);
        }
    }
}
