//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServicioCheckIn {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Servicios/", ConfigurationName="ServicioCheckIn.ServicioCheckIn")]
    public interface ServicioCheckIn {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Fecha del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioCheckIn/insertarCheckInRequest", ReplyAction="http://Servicios/ServicioCheckIn/insertarCheckInResponse")]
        CapaGUI.ServicioCheckIn.insertarCheckInResponse insertarCheckIn(CapaGUI.ServicioCheckIn.insertarCheckInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioCheckIn/insertarCheckInRequest", ReplyAction="http://Servicios/ServicioCheckIn/insertarCheckInResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioCheckIn.insertarCheckInResponse> insertarCheckInAsync(CapaGUI.ServicioCheckIn.insertarCheckInRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarCheckInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarCheckIn", Namespace="http://Servicios/", Order=0)]
        public CapaGUI.ServicioCheckIn.insertarCheckInRequestBody Body;
        
        public insertarCheckInRequest() {
        }
        
        public insertarCheckInRequest(CapaGUI.ServicioCheckIn.insertarCheckInRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class insertarCheckInRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Fecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int pagoRestante;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int idReserva;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int idRecursoHumano;
        
        public insertarCheckInRequestBody() {
        }
        
        public insertarCheckInRequestBody(string Fecha, int pagoRestante, int idReserva, int idRecursoHumano) {
            this.Fecha = Fecha;
            this.pagoRestante = pagoRestante;
            this.idReserva = idReserva;
            this.idRecursoHumano = idRecursoHumano;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarCheckInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarCheckInResponse", Namespace="http://Servicios/", Order=0)]
        public CapaGUI.ServicioCheckIn.insertarCheckInResponseBody Body;
        
        public insertarCheckInResponse() {
        }
        
        public insertarCheckInResponse(CapaGUI.ServicioCheckIn.insertarCheckInResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class insertarCheckInResponseBody {
        
        public insertarCheckInResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioCheckInChannel : CapaGUI.ServicioCheckIn.ServicioCheckIn, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioCheckInClient : System.ServiceModel.ClientBase<CapaGUI.ServicioCheckIn.ServicioCheckIn>, CapaGUI.ServicioCheckIn.ServicioCheckIn {
        
        public ServicioCheckInClient() {
        }
        
        public ServicioCheckInClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioCheckInClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCheckInClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCheckInClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioCheckIn.insertarCheckInResponse CapaGUI.ServicioCheckIn.ServicioCheckIn.insertarCheckIn(CapaGUI.ServicioCheckIn.insertarCheckInRequest request) {
            return base.Channel.insertarCheckIn(request);
        }
        
        public void insertarCheckIn(string Fecha, int pagoRestante, int idReserva, int idRecursoHumano) {
            CapaGUI.ServicioCheckIn.insertarCheckInRequest inValue = new CapaGUI.ServicioCheckIn.insertarCheckInRequest();
            inValue.Body = new CapaGUI.ServicioCheckIn.insertarCheckInRequestBody();
            inValue.Body.Fecha = Fecha;
            inValue.Body.pagoRestante = pagoRestante;
            inValue.Body.idReserva = idReserva;
            inValue.Body.idRecursoHumano = idRecursoHumano;
            CapaGUI.ServicioCheckIn.insertarCheckInResponse retVal = ((CapaGUI.ServicioCheckIn.ServicioCheckIn)(this)).insertarCheckIn(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioCheckIn.insertarCheckInResponse> CapaGUI.ServicioCheckIn.ServicioCheckIn.insertarCheckInAsync(CapaGUI.ServicioCheckIn.insertarCheckInRequest request) {
            return base.Channel.insertarCheckInAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioCheckIn.insertarCheckInResponse> insertarCheckInAsync(string Fecha, int pagoRestante, int idReserva, int idRecursoHumano) {
            CapaGUI.ServicioCheckIn.insertarCheckInRequest inValue = new CapaGUI.ServicioCheckIn.insertarCheckInRequest();
            inValue.Body = new CapaGUI.ServicioCheckIn.insertarCheckInRequestBody();
            inValue.Body.Fecha = Fecha;
            inValue.Body.pagoRestante = pagoRestante;
            inValue.Body.idReserva = idReserva;
            inValue.Body.idRecursoHumano = idRecursoHumano;
            return ((CapaGUI.ServicioCheckIn.ServicioCheckIn)(this)).insertarCheckInAsync(inValue);
        }
    }
}
