//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServicioCliente {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Servicios/", ConfigurationName="ServicioCliente.ServicioCliente")]
    public interface ServicioCliente {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioCliente/ListarClienteUsuarioRequest", ReplyAction="http://Servicios/ServicioCliente/ListarClienteUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaGUI.ServicioCliente.ListarClienteUsuarioResponse ListarClienteUsuario(CapaGUI.ServicioCliente.ListarClienteUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioCliente/ListarClienteUsuarioRequest", ReplyAction="http://Servicios/ServicioCliente/ListarClienteUsuarioResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioCliente.ListarClienteUsuarioResponse> ListarClienteUsuarioAsync(CapaGUI.ServicioCliente.ListarClienteUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioCliente/ListarClienteUsuarioDeshabilitadoRequest", ReplyAction="http://Servicios/ServicioCliente/ListarClienteUsuarioDeshabilitadoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaGUI.ServicioCliente.ListarClienteUsuarioDeshabilitadoResponse ListarClienteUsuarioDeshabilitado(CapaGUI.ServicioCliente.ListarClienteUsuarioDeshabilitadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioCliente/ListarClienteUsuarioDeshabilitadoRequest", ReplyAction="http://Servicios/ServicioCliente/ListarClienteUsuarioDeshabilitadoResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioCliente.ListarClienteUsuarioDeshabilitadoResponse> ListarClienteUsuarioDeshabilitadoAsync(CapaGUI.ServicioCliente.ListarClienteUsuarioDeshabilitadoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioCliente/loguearseByUsuarioRequest", ReplyAction="http://Servicios/ServicioCliente/loguearseByUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaGUI.ServicioCliente.loguearseByUsuarioResponse loguearseByUsuario(CapaGUI.ServicioCliente.loguearseByUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioCliente/loguearseByUsuarioRequest", ReplyAction="http://Servicios/ServicioCliente/loguearseByUsuarioResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioCliente.loguearseByUsuarioResponse> loguearseByUsuarioAsync(CapaGUI.ServicioCliente.loguearseByUsuarioRequest request);
        
        // CODEGEN: El parámetro 'Rut' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioCliente/updateUsuarioClienteRequest", ReplyAction="http://Servicios/ServicioCliente/updateUsuarioClienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUI.ServicioCliente.updateUsuarioClienteResponse updateUsuarioCliente(CapaGUI.ServicioCliente.updateUsuarioClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioCliente/updateUsuarioClienteRequest", ReplyAction="http://Servicios/ServicioCliente/updateUsuarioClienteResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioCliente.updateUsuarioClienteResponse> updateUsuarioClienteAsync(CapaGUI.ServicioCliente.updateUsuarioClienteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioCliente/getClienteByIdRequest", ReplyAction="http://Servicios/ServicioCliente/getClienteByIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaGUI.ServicioCliente.getClienteByIdResponse getClienteById(CapaGUI.ServicioCliente.getClienteByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioCliente/getClienteByIdRequest", ReplyAction="http://Servicios/ServicioCliente/getClienteByIdResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioCliente.getClienteByIdResponse> getClienteByIdAsync(CapaGUI.ServicioCliente.getClienteByIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioCliente/ListarClienteRequest", ReplyAction="http://Servicios/ServicioCliente/ListarClienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaGUI.ServicioCliente.ListarClienteResponse ListarCliente(CapaGUI.ServicioCliente.ListarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioCliente/ListarClienteRequest", ReplyAction="http://Servicios/ServicioCliente/ListarClienteResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioCliente.ListarClienteResponse> ListarClienteAsync(CapaGUI.ServicioCliente.ListarClienteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioCliente/getClienteByRutRequest", ReplyAction="http://Servicios/ServicioCliente/getClienteByRutResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaGUI.ServicioCliente.getClienteByRutResponse getClienteByRut(CapaGUI.ServicioCliente.getClienteByRutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioCliente/getClienteByRutRequest", ReplyAction="http://Servicios/ServicioCliente/getClienteByRutResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioCliente.getClienteByRutResponse> getClienteByRutAsync(CapaGUI.ServicioCliente.getClienteByRutRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class clienteUsuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string correoField;
        
        private string fechaNacimientoField;
        
        private int idPrivilegioField;
        
        private int idUsuarioField;
        
        private string nombreUsuarioField;
        
        private string nombresField;
        
        private string rutField;
        
        private int telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idPrivilegio {
            get {
                return this.idPrivilegioField;
            }
            set {
                this.idPrivilegioField = value;
                this.RaisePropertyChanged("idPrivilegio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                this.nombreUsuarioField = value;
                this.RaisePropertyChanged("nombreUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("rut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class cliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string correoField;
        
        private string fechaNacimientoField;
        
        private int idClienteField;
        
        private int idUsuarioField;
        
        private string nombresField;
        
        private string rutField;
        
        private int telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
                this.RaisePropertyChanged("idCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("rut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class clienteDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string contrasenaField;
        
        private string correoField;
        
        private string fechaNacimientoField;
        
        private int idClienteField;
        
        private int idUsuarioField;
        
        private string nombreUsuarioField;
        
        private string nombresField;
        
        private string privilegioField;
        
        private string rutField;
        
        private int telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
                this.RaisePropertyChanged("contrasena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
                this.RaisePropertyChanged("idCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                this.nombreUsuarioField = value;
                this.RaisePropertyChanged("nombreUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string privilegio {
            get {
                return this.privilegioField;
            }
            set {
                this.privilegioField = value;
                this.RaisePropertyChanged("privilegio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
                this.RaisePropertyChanged("rut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarClienteUsuario", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class ListarClienteUsuarioRequest {
        
        public ListarClienteUsuarioRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarClienteUsuarioResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class ListarClienteUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CapaGUI.ServicioCliente.clienteUsuario[] @return;
        
        public ListarClienteUsuarioResponse() {
        }
        
        public ListarClienteUsuarioResponse(CapaGUI.ServicioCliente.clienteUsuario[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarClienteUsuarioDeshabilitado", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class ListarClienteUsuarioDeshabilitadoRequest {
        
        public ListarClienteUsuarioDeshabilitadoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarClienteUsuarioDeshabilitadoResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class ListarClienteUsuarioDeshabilitadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CapaGUI.ServicioCliente.clienteUsuario[] @return;
        
        public ListarClienteUsuarioDeshabilitadoResponse() {
        }
        
        public ListarClienteUsuarioDeshabilitadoResponse(CapaGUI.ServicioCliente.clienteUsuario[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loguearseByUsuario", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class loguearseByUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuarito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrasena;
        
        public loguearseByUsuarioRequest() {
        }
        
        public loguearseByUsuarioRequest(string usuarito, string contrasena) {
            this.usuarito = usuarito;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loguearseByUsuarioResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class loguearseByUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public loguearseByUsuarioResponse() {
        }
        
        public loguearseByUsuarioResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateUsuarioCliente", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class updateUsuarioClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Rut;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Nombres;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ApellidoPaterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ApellidoMaterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Correo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FechaNacimiento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int fono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NombreUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        public updateUsuarioClienteRequest() {
        }
        
        public updateUsuarioClienteRequest(string Rut, string Nombres, string ApellidoPaterno, string ApellidoMaterno, string Correo, string FechaNacimiento, int fono, string NombreUsuario, string Password, int idUsuario) {
            this.Rut = Rut;
            this.Nombres = Nombres;
            this.ApellidoPaterno = ApellidoPaterno;
            this.ApellidoMaterno = ApellidoMaterno;
            this.Correo = Correo;
            this.FechaNacimiento = FechaNacimiento;
            this.fono = fono;
            this.NombreUsuario = NombreUsuario;
            this.Password = Password;
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateUsuarioClienteResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class updateUsuarioClienteResponse {
        
        public updateUsuarioClienteResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getClienteById", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class getClienteByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idUsuario;
        
        public getClienteByIdRequest() {
        }
        
        public getClienteByIdRequest(int idUsuario) {
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getClienteByIdResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class getClienteByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CapaGUI.ServicioCliente.clienteDto @return;
        
        public getClienteByIdResponse() {
        }
        
        public getClienteByIdResponse(CapaGUI.ServicioCliente.clienteDto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarCliente", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class ListarClienteRequest {
        
        public ListarClienteRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarClienteResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class ListarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CapaGUI.ServicioCliente.cliente[] @return;
        
        public ListarClienteResponse() {
        }
        
        public ListarClienteResponse(CapaGUI.ServicioCliente.cliente[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getClienteByRut", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class getClienteByRutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Rut;
        
        public getClienteByRutRequest() {
        }
        
        public getClienteByRutRequest(string Rut) {
            this.Rut = Rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getClienteByRutResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class getClienteByRutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CapaGUI.ServicioCliente.clienteUsuario @return;
        
        public getClienteByRutResponse() {
        }
        
        public getClienteByRutResponse(CapaGUI.ServicioCliente.clienteUsuario @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioClienteChannel : CapaGUI.ServicioCliente.ServicioCliente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClienteClient : System.ServiceModel.ClientBase<CapaGUI.ServicioCliente.ServicioCliente>, CapaGUI.ServicioCliente.ServicioCliente {
        
        public ServicioClienteClient() {
        }
        
        public ServicioClienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioCliente.ListarClienteUsuarioResponse CapaGUI.ServicioCliente.ServicioCliente.ListarClienteUsuario(CapaGUI.ServicioCliente.ListarClienteUsuarioRequest request) {
            return base.Channel.ListarClienteUsuario(request);
        }
        
        public CapaGUI.ServicioCliente.clienteUsuario[] ListarClienteUsuario() {
            CapaGUI.ServicioCliente.ListarClienteUsuarioRequest inValue = new CapaGUI.ServicioCliente.ListarClienteUsuarioRequest();
            CapaGUI.ServicioCliente.ListarClienteUsuarioResponse retVal = ((CapaGUI.ServicioCliente.ServicioCliente)(this)).ListarClienteUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioCliente.ListarClienteUsuarioResponse> CapaGUI.ServicioCliente.ServicioCliente.ListarClienteUsuarioAsync(CapaGUI.ServicioCliente.ListarClienteUsuarioRequest request) {
            return base.Channel.ListarClienteUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioCliente.ListarClienteUsuarioResponse> ListarClienteUsuarioAsync() {
            CapaGUI.ServicioCliente.ListarClienteUsuarioRequest inValue = new CapaGUI.ServicioCliente.ListarClienteUsuarioRequest();
            return ((CapaGUI.ServicioCliente.ServicioCliente)(this)).ListarClienteUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioCliente.ListarClienteUsuarioDeshabilitadoResponse CapaGUI.ServicioCliente.ServicioCliente.ListarClienteUsuarioDeshabilitado(CapaGUI.ServicioCliente.ListarClienteUsuarioDeshabilitadoRequest request) {
            return base.Channel.ListarClienteUsuarioDeshabilitado(request);
        }
        
        public CapaGUI.ServicioCliente.clienteUsuario[] ListarClienteUsuarioDeshabilitado() {
            CapaGUI.ServicioCliente.ListarClienteUsuarioDeshabilitadoRequest inValue = new CapaGUI.ServicioCliente.ListarClienteUsuarioDeshabilitadoRequest();
            CapaGUI.ServicioCliente.ListarClienteUsuarioDeshabilitadoResponse retVal = ((CapaGUI.ServicioCliente.ServicioCliente)(this)).ListarClienteUsuarioDeshabilitado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioCliente.ListarClienteUsuarioDeshabilitadoResponse> CapaGUI.ServicioCliente.ServicioCliente.ListarClienteUsuarioDeshabilitadoAsync(CapaGUI.ServicioCliente.ListarClienteUsuarioDeshabilitadoRequest request) {
            return base.Channel.ListarClienteUsuarioDeshabilitadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioCliente.ListarClienteUsuarioDeshabilitadoResponse> ListarClienteUsuarioDeshabilitadoAsync() {
            CapaGUI.ServicioCliente.ListarClienteUsuarioDeshabilitadoRequest inValue = new CapaGUI.ServicioCliente.ListarClienteUsuarioDeshabilitadoRequest();
            return ((CapaGUI.ServicioCliente.ServicioCliente)(this)).ListarClienteUsuarioDeshabilitadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioCliente.loguearseByUsuarioResponse CapaGUI.ServicioCliente.ServicioCliente.loguearseByUsuario(CapaGUI.ServicioCliente.loguearseByUsuarioRequest request) {
            return base.Channel.loguearseByUsuario(request);
        }
        
        public string loguearseByUsuario(string usuarito, string contrasena) {
            CapaGUI.ServicioCliente.loguearseByUsuarioRequest inValue = new CapaGUI.ServicioCliente.loguearseByUsuarioRequest();
            inValue.usuarito = usuarito;
            inValue.contrasena = contrasena;
            CapaGUI.ServicioCliente.loguearseByUsuarioResponse retVal = ((CapaGUI.ServicioCliente.ServicioCliente)(this)).loguearseByUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioCliente.loguearseByUsuarioResponse> CapaGUI.ServicioCliente.ServicioCliente.loguearseByUsuarioAsync(CapaGUI.ServicioCliente.loguearseByUsuarioRequest request) {
            return base.Channel.loguearseByUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioCliente.loguearseByUsuarioResponse> loguearseByUsuarioAsync(string usuarito, string contrasena) {
            CapaGUI.ServicioCliente.loguearseByUsuarioRequest inValue = new CapaGUI.ServicioCliente.loguearseByUsuarioRequest();
            inValue.usuarito = usuarito;
            inValue.contrasena = contrasena;
            return ((CapaGUI.ServicioCliente.ServicioCliente)(this)).loguearseByUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioCliente.updateUsuarioClienteResponse CapaGUI.ServicioCliente.ServicioCliente.updateUsuarioCliente(CapaGUI.ServicioCliente.updateUsuarioClienteRequest request) {
            return base.Channel.updateUsuarioCliente(request);
        }
        
        public void updateUsuarioCliente(string Rut, string Nombres, string ApellidoPaterno, string ApellidoMaterno, string Correo, string FechaNacimiento, int fono, string NombreUsuario, string Password, int idUsuario) {
            CapaGUI.ServicioCliente.updateUsuarioClienteRequest inValue = new CapaGUI.ServicioCliente.updateUsuarioClienteRequest();
            inValue.Rut = Rut;
            inValue.Nombres = Nombres;
            inValue.ApellidoPaterno = ApellidoPaterno;
            inValue.ApellidoMaterno = ApellidoMaterno;
            inValue.Correo = Correo;
            inValue.FechaNacimiento = FechaNacimiento;
            inValue.fono = fono;
            inValue.NombreUsuario = NombreUsuario;
            inValue.Password = Password;
            inValue.idUsuario = idUsuario;
            CapaGUI.ServicioCliente.updateUsuarioClienteResponse retVal = ((CapaGUI.ServicioCliente.ServicioCliente)(this)).updateUsuarioCliente(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioCliente.updateUsuarioClienteResponse> CapaGUI.ServicioCliente.ServicioCliente.updateUsuarioClienteAsync(CapaGUI.ServicioCliente.updateUsuarioClienteRequest request) {
            return base.Channel.updateUsuarioClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioCliente.updateUsuarioClienteResponse> updateUsuarioClienteAsync(string Rut, string Nombres, string ApellidoPaterno, string ApellidoMaterno, string Correo, string FechaNacimiento, int fono, string NombreUsuario, string Password, int idUsuario) {
            CapaGUI.ServicioCliente.updateUsuarioClienteRequest inValue = new CapaGUI.ServicioCliente.updateUsuarioClienteRequest();
            inValue.Rut = Rut;
            inValue.Nombres = Nombres;
            inValue.ApellidoPaterno = ApellidoPaterno;
            inValue.ApellidoMaterno = ApellidoMaterno;
            inValue.Correo = Correo;
            inValue.FechaNacimiento = FechaNacimiento;
            inValue.fono = fono;
            inValue.NombreUsuario = NombreUsuario;
            inValue.Password = Password;
            inValue.idUsuario = idUsuario;
            return ((CapaGUI.ServicioCliente.ServicioCliente)(this)).updateUsuarioClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioCliente.getClienteByIdResponse CapaGUI.ServicioCliente.ServicioCliente.getClienteById(CapaGUI.ServicioCliente.getClienteByIdRequest request) {
            return base.Channel.getClienteById(request);
        }
        
        public CapaGUI.ServicioCliente.clienteDto getClienteById(int idUsuario) {
            CapaGUI.ServicioCliente.getClienteByIdRequest inValue = new CapaGUI.ServicioCliente.getClienteByIdRequest();
            inValue.idUsuario = idUsuario;
            CapaGUI.ServicioCliente.getClienteByIdResponse retVal = ((CapaGUI.ServicioCliente.ServicioCliente)(this)).getClienteById(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioCliente.getClienteByIdResponse> CapaGUI.ServicioCliente.ServicioCliente.getClienteByIdAsync(CapaGUI.ServicioCliente.getClienteByIdRequest request) {
            return base.Channel.getClienteByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioCliente.getClienteByIdResponse> getClienteByIdAsync(int idUsuario) {
            CapaGUI.ServicioCliente.getClienteByIdRequest inValue = new CapaGUI.ServicioCliente.getClienteByIdRequest();
            inValue.idUsuario = idUsuario;
            return ((CapaGUI.ServicioCliente.ServicioCliente)(this)).getClienteByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioCliente.ListarClienteResponse CapaGUI.ServicioCliente.ServicioCliente.ListarCliente(CapaGUI.ServicioCliente.ListarClienteRequest request) {
            return base.Channel.ListarCliente(request);
        }
        
        public CapaGUI.ServicioCliente.cliente[] ListarCliente() {
            CapaGUI.ServicioCliente.ListarClienteRequest inValue = new CapaGUI.ServicioCliente.ListarClienteRequest();
            CapaGUI.ServicioCliente.ListarClienteResponse retVal = ((CapaGUI.ServicioCliente.ServicioCliente)(this)).ListarCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioCliente.ListarClienteResponse> CapaGUI.ServicioCliente.ServicioCliente.ListarClienteAsync(CapaGUI.ServicioCliente.ListarClienteRequest request) {
            return base.Channel.ListarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioCliente.ListarClienteResponse> ListarClienteAsync() {
            CapaGUI.ServicioCliente.ListarClienteRequest inValue = new CapaGUI.ServicioCliente.ListarClienteRequest();
            return ((CapaGUI.ServicioCliente.ServicioCliente)(this)).ListarClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioCliente.getClienteByRutResponse CapaGUI.ServicioCliente.ServicioCliente.getClienteByRut(CapaGUI.ServicioCliente.getClienteByRutRequest request) {
            return base.Channel.getClienteByRut(request);
        }
        
        public CapaGUI.ServicioCliente.clienteUsuario getClienteByRut(string Rut) {
            CapaGUI.ServicioCliente.getClienteByRutRequest inValue = new CapaGUI.ServicioCliente.getClienteByRutRequest();
            inValue.Rut = Rut;
            CapaGUI.ServicioCliente.getClienteByRutResponse retVal = ((CapaGUI.ServicioCliente.ServicioCliente)(this)).getClienteByRut(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioCliente.getClienteByRutResponse> CapaGUI.ServicioCliente.ServicioCliente.getClienteByRutAsync(CapaGUI.ServicioCliente.getClienteByRutRequest request) {
            return base.Channel.getClienteByRutAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioCliente.getClienteByRutResponse> getClienteByRutAsync(string Rut) {
            CapaGUI.ServicioCliente.getClienteByRutRequest inValue = new CapaGUI.ServicioCliente.getClienteByRutRequest();
            inValue.Rut = Rut;
            return ((CapaGUI.ServicioCliente.ServicioCliente)(this)).getClienteByRutAsync(inValue);
        }
    }
}
