//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServicioUsuario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Servicios/", ConfigurationName="ServicioUsuario.ServicioUsuario")]
    public interface ServicioUsuario {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento V_NOMBRE_USUARIO del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioUsuario/ActualizarUsuarioRequest", ReplyAction="http://Servicios/ServicioUsuario/ActualizarUsuarioResponse")]
        CapaGUI.ServicioUsuario.ActualizarUsuarioResponse ActualizarUsuario(CapaGUI.ServicioUsuario.ActualizarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioUsuario/ActualizarUsuarioRequest", ReplyAction="http://Servicios/ServicioUsuario/ActualizarUsuarioResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioUsuario.ActualizarUsuarioResponse> ActualizarUsuarioAsync(CapaGUI.ServicioUsuario.ActualizarUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://Servicios/).
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioUsuario/EliminarClienteUsuarioRequest", ReplyAction="http://Servicios/ServicioUsuario/EliminarClienteUsuarioResponse")]
        CapaGUI.ServicioUsuario.EliminarClienteUsuarioResponse EliminarClienteUsuario(CapaGUI.ServicioUsuario.EliminarClienteUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioUsuario/EliminarClienteUsuarioRequest", ReplyAction="http://Servicios/ServicioUsuario/EliminarClienteUsuarioResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioUsuario.EliminarClienteUsuarioResponse> EliminarClienteUsuarioAsync(CapaGUI.ServicioUsuario.EliminarClienteUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://Servicios/).
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioUsuario/autenticarUsuarioRequest", ReplyAction="http://Servicios/ServicioUsuario/autenticarUsuarioResponse")]
        CapaGUI.ServicioUsuario.autenticarUsuarioResponse autenticarUsuario(CapaGUI.ServicioUsuario.autenticarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioUsuario/autenticarUsuarioRequest", ReplyAction="http://Servicios/ServicioUsuario/autenticarUsuarioResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioUsuario.autenticarUsuarioResponse> autenticarUsuarioAsync(CapaGUI.ServicioUsuario.autenticarUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento V_RUT del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioUsuario/ingresarUsuario2Request", ReplyAction="http://Servicios/ServicioUsuario/ingresarUsuario2Response")]
        CapaGUI.ServicioUsuario.ingresarUsuario2Response ingresarUsuario2(CapaGUI.ServicioUsuario.ingresarUsuario2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioUsuario/ingresarUsuario2Request", ReplyAction="http://Servicios/ServicioUsuario/ingresarUsuario2Response")]
        System.Threading.Tasks.Task<CapaGUI.ServicioUsuario.ingresarUsuario2Response> ingresarUsuario2Async(CapaGUI.ServicioUsuario.ingresarUsuario2Request request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombreUsuario del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioUsuario/ingresarUsuarioRequest", ReplyAction="http://Servicios/ServicioUsuario/ingresarUsuarioResponse")]
        CapaGUI.ServicioUsuario.ingresarUsuarioResponse ingresarUsuario(CapaGUI.ServicioUsuario.ingresarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioUsuario/ingresarUsuarioRequest", ReplyAction="http://Servicios/ServicioUsuario/ingresarUsuarioResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioUsuario.ingresarUsuarioResponse> ingresarUsuarioAsync(CapaGUI.ServicioUsuario.ingresarUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarUsuario", Namespace="http://Servicios/", Order=0)]
        public CapaGUI.ServicioUsuario.ActualizarUsuarioRequestBody Body;
        
        public ActualizarUsuarioRequest() {
        }
        
        public ActualizarUsuarioRequest(CapaGUI.ServicioUsuario.ActualizarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ActualizarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int V_ID_USUARIO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string V_NOMBRE_USUARIO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string V_CONTRASENA;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int V_ID_PRIVILEGIO;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int V_ID_ESTADO;
        
        public ActualizarUsuarioRequestBody() {
        }
        
        public ActualizarUsuarioRequestBody(int V_ID_USUARIO, string V_NOMBRE_USUARIO, string V_CONTRASENA, int V_ID_PRIVILEGIO, int V_ID_ESTADO) {
            this.V_ID_USUARIO = V_ID_USUARIO;
            this.V_NOMBRE_USUARIO = V_NOMBRE_USUARIO;
            this.V_CONTRASENA = V_CONTRASENA;
            this.V_ID_PRIVILEGIO = V_ID_PRIVILEGIO;
            this.V_ID_ESTADO = V_ID_ESTADO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarUsuarioResponse", Namespace="http://Servicios/", Order=0)]
        public CapaGUI.ServicioUsuario.ActualizarUsuarioResponseBody Body;
        
        public ActualizarUsuarioResponse() {
        }
        
        public ActualizarUsuarioResponse(CapaGUI.ServicioUsuario.ActualizarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ActualizarUsuarioResponseBody {
        
        public ActualizarUsuarioResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarClienteUsuario", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class EliminarClienteUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int idUsuario;
        
        public EliminarClienteUsuarioRequest() {
        }
        
        public EliminarClienteUsuarioRequest(int idUsuario) {
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarClienteUsuarioResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class EliminarClienteUsuarioResponse {
        
        public EliminarClienteUsuarioResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="autenticarUsuario", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class autenticarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int V_ID_USUARIO;
        
        public autenticarUsuarioRequest() {
        }
        
        public autenticarUsuarioRequest(int V_ID_USUARIO) {
            this.V_ID_USUARIO = V_ID_USUARIO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="autenticarUsuarioResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class autenticarUsuarioResponse {
        
        public autenticarUsuarioResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ingresarUsuario2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ingresarUsuario2", Namespace="http://Servicios/", Order=0)]
        public CapaGUI.ServicioUsuario.ingresarUsuario2RequestBody Body;
        
        public ingresarUsuario2Request() {
        }
        
        public ingresarUsuario2Request(CapaGUI.ServicioUsuario.ingresarUsuario2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ingresarUsuario2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string V_RUT;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string V_NOMBRES;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string V_APELLIDO_PATERNO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string V_APELLIDO_MATERNO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string V_CORREO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string V_FECHA_NACIMIENTO;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int V_TELEFONO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string V_NOMBRE_USUARIO;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string V_CONTRASENA;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int V_ID_PRIVILEGIO;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int V_ID_ESTADO;
        
        public ingresarUsuario2RequestBody() {
        }
        
        public ingresarUsuario2RequestBody(string V_RUT, string V_NOMBRES, string V_APELLIDO_PATERNO, string V_APELLIDO_MATERNO, string V_CORREO, string V_FECHA_NACIMIENTO, int V_TELEFONO, string V_NOMBRE_USUARIO, string V_CONTRASENA, int V_ID_PRIVILEGIO, int V_ID_ESTADO) {
            this.V_RUT = V_RUT;
            this.V_NOMBRES = V_NOMBRES;
            this.V_APELLIDO_PATERNO = V_APELLIDO_PATERNO;
            this.V_APELLIDO_MATERNO = V_APELLIDO_MATERNO;
            this.V_CORREO = V_CORREO;
            this.V_FECHA_NACIMIENTO = V_FECHA_NACIMIENTO;
            this.V_TELEFONO = V_TELEFONO;
            this.V_NOMBRE_USUARIO = V_NOMBRE_USUARIO;
            this.V_CONTRASENA = V_CONTRASENA;
            this.V_ID_PRIVILEGIO = V_ID_PRIVILEGIO;
            this.V_ID_ESTADO = V_ID_ESTADO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ingresarUsuario2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ingresarUsuario2Response", Namespace="http://Servicios/", Order=0)]
        public CapaGUI.ServicioUsuario.ingresarUsuario2ResponseBody Body;
        
        public ingresarUsuario2Response() {
        }
        
        public ingresarUsuario2Response(CapaGUI.ServicioUsuario.ingresarUsuario2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ingresarUsuario2ResponseBody {
        
        public ingresarUsuario2ResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ingresarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ingresarUsuario", Namespace="http://Servicios/", Order=0)]
        public CapaGUI.ServicioUsuario.ingresarUsuarioRequestBody Body;
        
        public ingresarUsuarioRequest() {
        }
        
        public ingresarUsuarioRequest(CapaGUI.ServicioUsuario.ingresarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ingresarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombreUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contrasena;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int id_Privilegio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int id_Estado;
        
        public ingresarUsuarioRequestBody() {
        }
        
        public ingresarUsuarioRequestBody(string nombreUsuario, string contrasena, int id_Privilegio, int id_Estado) {
            this.nombreUsuario = nombreUsuario;
            this.contrasena = contrasena;
            this.id_Privilegio = id_Privilegio;
            this.id_Estado = id_Estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ingresarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ingresarUsuarioResponse", Namespace="http://Servicios/", Order=0)]
        public CapaGUI.ServicioUsuario.ingresarUsuarioResponseBody Body;
        
        public ingresarUsuarioResponse() {
        }
        
        public ingresarUsuarioResponse(CapaGUI.ServicioUsuario.ingresarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ingresarUsuarioResponseBody {
        
        public ingresarUsuarioResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioUsuarioChannel : CapaGUI.ServicioUsuario.ServicioUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioUsuarioClient : System.ServiceModel.ClientBase<CapaGUI.ServicioUsuario.ServicioUsuario>, CapaGUI.ServicioUsuario.ServicioUsuario {
        
        public ServicioUsuarioClient() {
        }
        
        public ServicioUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioUsuario.ActualizarUsuarioResponse CapaGUI.ServicioUsuario.ServicioUsuario.ActualizarUsuario(CapaGUI.ServicioUsuario.ActualizarUsuarioRequest request) {
            return base.Channel.ActualizarUsuario(request);
        }
        
        public void ActualizarUsuario(int V_ID_USUARIO, string V_NOMBRE_USUARIO, string V_CONTRASENA, int V_ID_PRIVILEGIO, int V_ID_ESTADO) {
            CapaGUI.ServicioUsuario.ActualizarUsuarioRequest inValue = new CapaGUI.ServicioUsuario.ActualizarUsuarioRequest();
            inValue.Body = new CapaGUI.ServicioUsuario.ActualizarUsuarioRequestBody();
            inValue.Body.V_ID_USUARIO = V_ID_USUARIO;
            inValue.Body.V_NOMBRE_USUARIO = V_NOMBRE_USUARIO;
            inValue.Body.V_CONTRASENA = V_CONTRASENA;
            inValue.Body.V_ID_PRIVILEGIO = V_ID_PRIVILEGIO;
            inValue.Body.V_ID_ESTADO = V_ID_ESTADO;
            CapaGUI.ServicioUsuario.ActualizarUsuarioResponse retVal = ((CapaGUI.ServicioUsuario.ServicioUsuario)(this)).ActualizarUsuario(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioUsuario.ActualizarUsuarioResponse> CapaGUI.ServicioUsuario.ServicioUsuario.ActualizarUsuarioAsync(CapaGUI.ServicioUsuario.ActualizarUsuarioRequest request) {
            return base.Channel.ActualizarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioUsuario.ActualizarUsuarioResponse> ActualizarUsuarioAsync(int V_ID_USUARIO, string V_NOMBRE_USUARIO, string V_CONTRASENA, int V_ID_PRIVILEGIO, int V_ID_ESTADO) {
            CapaGUI.ServicioUsuario.ActualizarUsuarioRequest inValue = new CapaGUI.ServicioUsuario.ActualizarUsuarioRequest();
            inValue.Body = new CapaGUI.ServicioUsuario.ActualizarUsuarioRequestBody();
            inValue.Body.V_ID_USUARIO = V_ID_USUARIO;
            inValue.Body.V_NOMBRE_USUARIO = V_NOMBRE_USUARIO;
            inValue.Body.V_CONTRASENA = V_CONTRASENA;
            inValue.Body.V_ID_PRIVILEGIO = V_ID_PRIVILEGIO;
            inValue.Body.V_ID_ESTADO = V_ID_ESTADO;
            return ((CapaGUI.ServicioUsuario.ServicioUsuario)(this)).ActualizarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioUsuario.EliminarClienteUsuarioResponse CapaGUI.ServicioUsuario.ServicioUsuario.EliminarClienteUsuario(CapaGUI.ServicioUsuario.EliminarClienteUsuarioRequest request) {
            return base.Channel.EliminarClienteUsuario(request);
        }
        
        public void EliminarClienteUsuario(int idUsuario) {
            CapaGUI.ServicioUsuario.EliminarClienteUsuarioRequest inValue = new CapaGUI.ServicioUsuario.EliminarClienteUsuarioRequest();
            inValue.idUsuario = idUsuario;
            CapaGUI.ServicioUsuario.EliminarClienteUsuarioResponse retVal = ((CapaGUI.ServicioUsuario.ServicioUsuario)(this)).EliminarClienteUsuario(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioUsuario.EliminarClienteUsuarioResponse> CapaGUI.ServicioUsuario.ServicioUsuario.EliminarClienteUsuarioAsync(CapaGUI.ServicioUsuario.EliminarClienteUsuarioRequest request) {
            return base.Channel.EliminarClienteUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioUsuario.EliminarClienteUsuarioResponse> EliminarClienteUsuarioAsync(int idUsuario) {
            CapaGUI.ServicioUsuario.EliminarClienteUsuarioRequest inValue = new CapaGUI.ServicioUsuario.EliminarClienteUsuarioRequest();
            inValue.idUsuario = idUsuario;
            return ((CapaGUI.ServicioUsuario.ServicioUsuario)(this)).EliminarClienteUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioUsuario.autenticarUsuarioResponse CapaGUI.ServicioUsuario.ServicioUsuario.autenticarUsuario(CapaGUI.ServicioUsuario.autenticarUsuarioRequest request) {
            return base.Channel.autenticarUsuario(request);
        }
        
        public void autenticarUsuario(int V_ID_USUARIO) {
            CapaGUI.ServicioUsuario.autenticarUsuarioRequest inValue = new CapaGUI.ServicioUsuario.autenticarUsuarioRequest();
            inValue.V_ID_USUARIO = V_ID_USUARIO;
            CapaGUI.ServicioUsuario.autenticarUsuarioResponse retVal = ((CapaGUI.ServicioUsuario.ServicioUsuario)(this)).autenticarUsuario(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioUsuario.autenticarUsuarioResponse> CapaGUI.ServicioUsuario.ServicioUsuario.autenticarUsuarioAsync(CapaGUI.ServicioUsuario.autenticarUsuarioRequest request) {
            return base.Channel.autenticarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioUsuario.autenticarUsuarioResponse> autenticarUsuarioAsync(int V_ID_USUARIO) {
            CapaGUI.ServicioUsuario.autenticarUsuarioRequest inValue = new CapaGUI.ServicioUsuario.autenticarUsuarioRequest();
            inValue.V_ID_USUARIO = V_ID_USUARIO;
            return ((CapaGUI.ServicioUsuario.ServicioUsuario)(this)).autenticarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioUsuario.ingresarUsuario2Response CapaGUI.ServicioUsuario.ServicioUsuario.ingresarUsuario2(CapaGUI.ServicioUsuario.ingresarUsuario2Request request) {
            return base.Channel.ingresarUsuario2(request);
        }
        
        public void ingresarUsuario2(string V_RUT, string V_NOMBRES, string V_APELLIDO_PATERNO, string V_APELLIDO_MATERNO, string V_CORREO, string V_FECHA_NACIMIENTO, int V_TELEFONO, string V_NOMBRE_USUARIO, string V_CONTRASENA, int V_ID_PRIVILEGIO, int V_ID_ESTADO) {
            CapaGUI.ServicioUsuario.ingresarUsuario2Request inValue = new CapaGUI.ServicioUsuario.ingresarUsuario2Request();
            inValue.Body = new CapaGUI.ServicioUsuario.ingresarUsuario2RequestBody();
            inValue.Body.V_RUT = V_RUT;
            inValue.Body.V_NOMBRES = V_NOMBRES;
            inValue.Body.V_APELLIDO_PATERNO = V_APELLIDO_PATERNO;
            inValue.Body.V_APELLIDO_MATERNO = V_APELLIDO_MATERNO;
            inValue.Body.V_CORREO = V_CORREO;
            inValue.Body.V_FECHA_NACIMIENTO = V_FECHA_NACIMIENTO;
            inValue.Body.V_TELEFONO = V_TELEFONO;
            inValue.Body.V_NOMBRE_USUARIO = V_NOMBRE_USUARIO;
            inValue.Body.V_CONTRASENA = V_CONTRASENA;
            inValue.Body.V_ID_PRIVILEGIO = V_ID_PRIVILEGIO;
            inValue.Body.V_ID_ESTADO = V_ID_ESTADO;
            CapaGUI.ServicioUsuario.ingresarUsuario2Response retVal = ((CapaGUI.ServicioUsuario.ServicioUsuario)(this)).ingresarUsuario2(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioUsuario.ingresarUsuario2Response> CapaGUI.ServicioUsuario.ServicioUsuario.ingresarUsuario2Async(CapaGUI.ServicioUsuario.ingresarUsuario2Request request) {
            return base.Channel.ingresarUsuario2Async(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioUsuario.ingresarUsuario2Response> ingresarUsuario2Async(string V_RUT, string V_NOMBRES, string V_APELLIDO_PATERNO, string V_APELLIDO_MATERNO, string V_CORREO, string V_FECHA_NACIMIENTO, int V_TELEFONO, string V_NOMBRE_USUARIO, string V_CONTRASENA, int V_ID_PRIVILEGIO, int V_ID_ESTADO) {
            CapaGUI.ServicioUsuario.ingresarUsuario2Request inValue = new CapaGUI.ServicioUsuario.ingresarUsuario2Request();
            inValue.Body = new CapaGUI.ServicioUsuario.ingresarUsuario2RequestBody();
            inValue.Body.V_RUT = V_RUT;
            inValue.Body.V_NOMBRES = V_NOMBRES;
            inValue.Body.V_APELLIDO_PATERNO = V_APELLIDO_PATERNO;
            inValue.Body.V_APELLIDO_MATERNO = V_APELLIDO_MATERNO;
            inValue.Body.V_CORREO = V_CORREO;
            inValue.Body.V_FECHA_NACIMIENTO = V_FECHA_NACIMIENTO;
            inValue.Body.V_TELEFONO = V_TELEFONO;
            inValue.Body.V_NOMBRE_USUARIO = V_NOMBRE_USUARIO;
            inValue.Body.V_CONTRASENA = V_CONTRASENA;
            inValue.Body.V_ID_PRIVILEGIO = V_ID_PRIVILEGIO;
            inValue.Body.V_ID_ESTADO = V_ID_ESTADO;
            return ((CapaGUI.ServicioUsuario.ServicioUsuario)(this)).ingresarUsuario2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioUsuario.ingresarUsuarioResponse CapaGUI.ServicioUsuario.ServicioUsuario.ingresarUsuario(CapaGUI.ServicioUsuario.ingresarUsuarioRequest request) {
            return base.Channel.ingresarUsuario(request);
        }
        
        public void ingresarUsuario(string nombreUsuario, string contrasena, int id_Privilegio, int id_Estado) {
            CapaGUI.ServicioUsuario.ingresarUsuarioRequest inValue = new CapaGUI.ServicioUsuario.ingresarUsuarioRequest();
            inValue.Body = new CapaGUI.ServicioUsuario.ingresarUsuarioRequestBody();
            inValue.Body.nombreUsuario = nombreUsuario;
            inValue.Body.contrasena = contrasena;
            inValue.Body.id_Privilegio = id_Privilegio;
            inValue.Body.id_Estado = id_Estado;
            CapaGUI.ServicioUsuario.ingresarUsuarioResponse retVal = ((CapaGUI.ServicioUsuario.ServicioUsuario)(this)).ingresarUsuario(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioUsuario.ingresarUsuarioResponse> CapaGUI.ServicioUsuario.ServicioUsuario.ingresarUsuarioAsync(CapaGUI.ServicioUsuario.ingresarUsuarioRequest request) {
            return base.Channel.ingresarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioUsuario.ingresarUsuarioResponse> ingresarUsuarioAsync(string nombreUsuario, string contrasena, int id_Privilegio, int id_Estado) {
            CapaGUI.ServicioUsuario.ingresarUsuarioRequest inValue = new CapaGUI.ServicioUsuario.ingresarUsuarioRequest();
            inValue.Body = new CapaGUI.ServicioUsuario.ingresarUsuarioRequestBody();
            inValue.Body.nombreUsuario = nombreUsuario;
            inValue.Body.contrasena = contrasena;
            inValue.Body.id_Privilegio = id_Privilegio;
            inValue.Body.id_Estado = id_Estado;
            return ((CapaGUI.ServicioUsuario.ServicioUsuario)(this)).ingresarUsuarioAsync(inValue);
        }
    }
}
