//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServicioLogin {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Servicios/", ConfigurationName="ServicioLogin.ServicioLogin")]
    public interface ServicioLogin {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://Servicios/).
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioLogin/getidByUserIDRequest", ReplyAction="http://Servicios/ServicioLogin/getidByUserIDResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaGUI.ServicioLogin.getidByUserIDResponse getidByUserID(CapaGUI.ServicioLogin.getidByUserIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioLogin/getidByUserIDRequest", ReplyAction="http://Servicios/ServicioLogin/getidByUserIDResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioLogin.getidByUserIDResponse> getidByUserIDAsync(CapaGUI.ServicioLogin.getidByUserIDRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuarito del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioLogin/getIdByUserNameRequest", ReplyAction="http://Servicios/ServicioLogin/getIdByUserNameResponse")]
        CapaGUI.ServicioLogin.getIdByUserNameResponse getIdByUserName(CapaGUI.ServicioLogin.getIdByUserNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioLogin/getIdByUserNameRequest", ReplyAction="http://Servicios/ServicioLogin/getIdByUserNameResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioLogin.getIdByUserNameResponse> getIdByUserNameAsync(CapaGUI.ServicioLogin.getIdByUserNameRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuarito del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioLogin/getIdByNameRequest", ReplyAction="http://Servicios/ServicioLogin/getIdByNameResponse")]
        CapaGUI.ServicioLogin.getIdByNameResponse getIdByName(CapaGUI.ServicioLogin.getIdByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioLogin/getIdByNameRequest", ReplyAction="http://Servicios/ServicioLogin/getIdByNameResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioLogin.getIdByNameResponse> getIdByNameAsync(CapaGUI.ServicioLogin.getIdByNameRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioLogin/getCorreoRequest", ReplyAction="http://Servicios/ServicioLogin/getCorreoResponse")]
        CapaGUI.ServicioLogin.getCorreoResponse getCorreo(CapaGUI.ServicioLogin.getCorreoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioLogin/getCorreoRequest", ReplyAction="http://Servicios/ServicioLogin/getCorreoResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioLogin.getCorreoResponse> getCorreoAsync(CapaGUI.ServicioLogin.getCorreoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuarito del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioLogin/loginRequest", ReplyAction="http://Servicios/ServicioLogin/loginResponse")]
        CapaGUI.ServicioLogin.loginResponse login(CapaGUI.ServicioLogin.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioLogin/loginRequest", ReplyAction="http://Servicios/ServicioLogin/loginResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioLogin.loginResponse> loginAsync(CapaGUI.ServicioLogin.loginRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioLogin/validarUsernameExistsRequest", ReplyAction="http://Servicios/ServicioLogin/validarUsernameExistsResponse")]
        CapaGUI.ServicioLogin.validarUsernameExistsResponse validarUsernameExists(CapaGUI.ServicioLogin.validarUsernameExistsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioLogin/validarUsernameExistsRequest", ReplyAction="http://Servicios/ServicioLogin/validarUsernameExistsResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioLogin.validarUsernameExistsResponse> validarUsernameExistsAsync(CapaGUI.ServicioLogin.validarUsernameExistsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getidByUserID", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class getidByUserIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int idUsuario;
        
        public getidByUserIDRequest() {
        }
        
        public getidByUserIDRequest(int idUsuario) {
            this.idUsuario = idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getidByUserIDResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class getidByUserIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public getidByUserIDResponse() {
        }
        
        public getidByUserIDResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getIdByUserNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getIdByUserName", Namespace="http://Servicios/", Order=0)]
        public CapaGUI.ServicioLogin.getIdByUserNameRequestBody Body;
        
        public getIdByUserNameRequest() {
        }
        
        public getIdByUserNameRequest(CapaGUI.ServicioLogin.getIdByUserNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getIdByUserNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuarito;
        
        public getIdByUserNameRequestBody() {
        }
        
        public getIdByUserNameRequestBody(string usuarito) {
            this.usuarito = usuarito;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getIdByUserNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getIdByUserNameResponse", Namespace="http://Servicios/", Order=0)]
        public CapaGUI.ServicioLogin.getIdByUserNameResponseBody Body;
        
        public getIdByUserNameResponse() {
        }
        
        public getIdByUserNameResponse(CapaGUI.ServicioLogin.getIdByUserNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getIdByUserNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public getIdByUserNameResponseBody() {
        }
        
        public getIdByUserNameResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getIdByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getIdByName", Namespace="http://Servicios/", Order=0)]
        public CapaGUI.ServicioLogin.getIdByNameRequestBody Body;
        
        public getIdByNameRequest() {
        }
        
        public getIdByNameRequest(CapaGUI.ServicioLogin.getIdByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getIdByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuarito;
        
        public getIdByNameRequestBody() {
        }
        
        public getIdByNameRequestBody(string usuarito) {
            this.usuarito = usuarito;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getIdByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getIdByNameResponse", Namespace="http://Servicios/", Order=0)]
        public CapaGUI.ServicioLogin.getIdByNameResponseBody Body;
        
        public getIdByNameResponse() {
        }
        
        public getIdByNameResponse(CapaGUI.ServicioLogin.getIdByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getIdByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public getIdByNameResponseBody() {
        }
        
        public getIdByNameResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCorreoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCorreo", Namespace="http://Servicios/", Order=0)]
        public CapaGUI.ServicioLogin.getCorreoRequestBody Body;
        
        public getCorreoRequest() {
        }
        
        public getCorreoRequest(CapaGUI.ServicioLogin.getCorreoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getCorreoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int usuarito;
        
        public getCorreoRequestBody() {
        }
        
        public getCorreoRequestBody(int usuarito) {
            this.usuarito = usuarito;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCorreoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCorreoResponse", Namespace="http://Servicios/", Order=0)]
        public CapaGUI.ServicioLogin.getCorreoResponseBody Body;
        
        public getCorreoResponse() {
        }
        
        public getCorreoResponse(CapaGUI.ServicioLogin.getCorreoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getCorreoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getCorreoResponseBody() {
        }
        
        public getCorreoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://Servicios/", Order=0)]
        public CapaGUI.ServicioLogin.loginRequestBody Body;
        
        public loginRequest() {
        }
        
        public loginRequest(CapaGUI.ServicioLogin.loginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class loginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuarito;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contrasena;
        
        public loginRequestBody() {
        }
        
        public loginRequestBody(string usuarito, string contrasena) {
            this.usuarito = usuarito;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://Servicios/", Order=0)]
        public CapaGUI.ServicioLogin.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(CapaGUI.ServicioLogin.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public loginResponseBody() {
        }
        
        public loginResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarUsernameExistsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarUsernameExists", Namespace="http://Servicios/", Order=0)]
        public CapaGUI.ServicioLogin.validarUsernameExistsRequestBody Body;
        
        public validarUsernameExistsRequest() {
        }
        
        public validarUsernameExistsRequest(CapaGUI.ServicioLogin.validarUsernameExistsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validarUsernameExistsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        public validarUsernameExistsRequestBody() {
        }
        
        public validarUsernameExistsRequestBody(string user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarUsernameExistsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarUsernameExistsResponse", Namespace="http://Servicios/", Order=0)]
        public CapaGUI.ServicioLogin.validarUsernameExistsResponseBody Body;
        
        public validarUsernameExistsResponse() {
        }
        
        public validarUsernameExistsResponse(CapaGUI.ServicioLogin.validarUsernameExistsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validarUsernameExistsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public validarUsernameExistsResponseBody() {
        }
        
        public validarUsernameExistsResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioLoginChannel : CapaGUI.ServicioLogin.ServicioLogin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioLoginClient : System.ServiceModel.ClientBase<CapaGUI.ServicioLogin.ServicioLogin>, CapaGUI.ServicioLogin.ServicioLogin {
        
        public ServicioLoginClient() {
        }
        
        public ServicioLoginClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioLoginClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioLoginClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioLoginClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioLogin.getidByUserIDResponse CapaGUI.ServicioLogin.ServicioLogin.getidByUserID(CapaGUI.ServicioLogin.getidByUserIDRequest request) {
            return base.Channel.getidByUserID(request);
        }
        
        public int getidByUserID(int idUsuario) {
            CapaGUI.ServicioLogin.getidByUserIDRequest inValue = new CapaGUI.ServicioLogin.getidByUserIDRequest();
            inValue.idUsuario = idUsuario;
            CapaGUI.ServicioLogin.getidByUserIDResponse retVal = ((CapaGUI.ServicioLogin.ServicioLogin)(this)).getidByUserID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioLogin.getidByUserIDResponse> CapaGUI.ServicioLogin.ServicioLogin.getidByUserIDAsync(CapaGUI.ServicioLogin.getidByUserIDRequest request) {
            return base.Channel.getidByUserIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioLogin.getidByUserIDResponse> getidByUserIDAsync(int idUsuario) {
            CapaGUI.ServicioLogin.getidByUserIDRequest inValue = new CapaGUI.ServicioLogin.getidByUserIDRequest();
            inValue.idUsuario = idUsuario;
            return ((CapaGUI.ServicioLogin.ServicioLogin)(this)).getidByUserIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioLogin.getIdByUserNameResponse CapaGUI.ServicioLogin.ServicioLogin.getIdByUserName(CapaGUI.ServicioLogin.getIdByUserNameRequest request) {
            return base.Channel.getIdByUserName(request);
        }
        
        public int getIdByUserName(string usuarito) {
            CapaGUI.ServicioLogin.getIdByUserNameRequest inValue = new CapaGUI.ServicioLogin.getIdByUserNameRequest();
            inValue.Body = new CapaGUI.ServicioLogin.getIdByUserNameRequestBody();
            inValue.Body.usuarito = usuarito;
            CapaGUI.ServicioLogin.getIdByUserNameResponse retVal = ((CapaGUI.ServicioLogin.ServicioLogin)(this)).getIdByUserName(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioLogin.getIdByUserNameResponse> CapaGUI.ServicioLogin.ServicioLogin.getIdByUserNameAsync(CapaGUI.ServicioLogin.getIdByUserNameRequest request) {
            return base.Channel.getIdByUserNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioLogin.getIdByUserNameResponse> getIdByUserNameAsync(string usuarito) {
            CapaGUI.ServicioLogin.getIdByUserNameRequest inValue = new CapaGUI.ServicioLogin.getIdByUserNameRequest();
            inValue.Body = new CapaGUI.ServicioLogin.getIdByUserNameRequestBody();
            inValue.Body.usuarito = usuarito;
            return ((CapaGUI.ServicioLogin.ServicioLogin)(this)).getIdByUserNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioLogin.getIdByNameResponse CapaGUI.ServicioLogin.ServicioLogin.getIdByName(CapaGUI.ServicioLogin.getIdByNameRequest request) {
            return base.Channel.getIdByName(request);
        }
        
        public int getIdByName(string usuarito) {
            CapaGUI.ServicioLogin.getIdByNameRequest inValue = new CapaGUI.ServicioLogin.getIdByNameRequest();
            inValue.Body = new CapaGUI.ServicioLogin.getIdByNameRequestBody();
            inValue.Body.usuarito = usuarito;
            CapaGUI.ServicioLogin.getIdByNameResponse retVal = ((CapaGUI.ServicioLogin.ServicioLogin)(this)).getIdByName(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioLogin.getIdByNameResponse> CapaGUI.ServicioLogin.ServicioLogin.getIdByNameAsync(CapaGUI.ServicioLogin.getIdByNameRequest request) {
            return base.Channel.getIdByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioLogin.getIdByNameResponse> getIdByNameAsync(string usuarito) {
            CapaGUI.ServicioLogin.getIdByNameRequest inValue = new CapaGUI.ServicioLogin.getIdByNameRequest();
            inValue.Body = new CapaGUI.ServicioLogin.getIdByNameRequestBody();
            inValue.Body.usuarito = usuarito;
            return ((CapaGUI.ServicioLogin.ServicioLogin)(this)).getIdByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioLogin.getCorreoResponse CapaGUI.ServicioLogin.ServicioLogin.getCorreo(CapaGUI.ServicioLogin.getCorreoRequest request) {
            return base.Channel.getCorreo(request);
        }
        
        public string getCorreo(int usuarito) {
            CapaGUI.ServicioLogin.getCorreoRequest inValue = new CapaGUI.ServicioLogin.getCorreoRequest();
            inValue.Body = new CapaGUI.ServicioLogin.getCorreoRequestBody();
            inValue.Body.usuarito = usuarito;
            CapaGUI.ServicioLogin.getCorreoResponse retVal = ((CapaGUI.ServicioLogin.ServicioLogin)(this)).getCorreo(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioLogin.getCorreoResponse> CapaGUI.ServicioLogin.ServicioLogin.getCorreoAsync(CapaGUI.ServicioLogin.getCorreoRequest request) {
            return base.Channel.getCorreoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioLogin.getCorreoResponse> getCorreoAsync(int usuarito) {
            CapaGUI.ServicioLogin.getCorreoRequest inValue = new CapaGUI.ServicioLogin.getCorreoRequest();
            inValue.Body = new CapaGUI.ServicioLogin.getCorreoRequestBody();
            inValue.Body.usuarito = usuarito;
            return ((CapaGUI.ServicioLogin.ServicioLogin)(this)).getCorreoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioLogin.loginResponse CapaGUI.ServicioLogin.ServicioLogin.login(CapaGUI.ServicioLogin.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public string login(string usuarito, string contrasena) {
            CapaGUI.ServicioLogin.loginRequest inValue = new CapaGUI.ServicioLogin.loginRequest();
            inValue.Body = new CapaGUI.ServicioLogin.loginRequestBody();
            inValue.Body.usuarito = usuarito;
            inValue.Body.contrasena = contrasena;
            CapaGUI.ServicioLogin.loginResponse retVal = ((CapaGUI.ServicioLogin.ServicioLogin)(this)).login(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioLogin.loginResponse> CapaGUI.ServicioLogin.ServicioLogin.loginAsync(CapaGUI.ServicioLogin.loginRequest request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioLogin.loginResponse> loginAsync(string usuarito, string contrasena) {
            CapaGUI.ServicioLogin.loginRequest inValue = new CapaGUI.ServicioLogin.loginRequest();
            inValue.Body = new CapaGUI.ServicioLogin.loginRequestBody();
            inValue.Body.usuarito = usuarito;
            inValue.Body.contrasena = contrasena;
            return ((CapaGUI.ServicioLogin.ServicioLogin)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioLogin.validarUsernameExistsResponse CapaGUI.ServicioLogin.ServicioLogin.validarUsernameExists(CapaGUI.ServicioLogin.validarUsernameExistsRequest request) {
            return base.Channel.validarUsernameExists(request);
        }
        
        public bool validarUsernameExists(string user) {
            CapaGUI.ServicioLogin.validarUsernameExistsRequest inValue = new CapaGUI.ServicioLogin.validarUsernameExistsRequest();
            inValue.Body = new CapaGUI.ServicioLogin.validarUsernameExistsRequestBody();
            inValue.Body.user = user;
            CapaGUI.ServicioLogin.validarUsernameExistsResponse retVal = ((CapaGUI.ServicioLogin.ServicioLogin)(this)).validarUsernameExists(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioLogin.validarUsernameExistsResponse> CapaGUI.ServicioLogin.ServicioLogin.validarUsernameExistsAsync(CapaGUI.ServicioLogin.validarUsernameExistsRequest request) {
            return base.Channel.validarUsernameExistsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioLogin.validarUsernameExistsResponse> validarUsernameExistsAsync(string user) {
            CapaGUI.ServicioLogin.validarUsernameExistsRequest inValue = new CapaGUI.ServicioLogin.validarUsernameExistsRequest();
            inValue.Body = new CapaGUI.ServicioLogin.validarUsernameExistsRequestBody();
            inValue.Body.user = user;
            return ((CapaGUI.ServicioLogin.ServicioLogin)(this)).validarUsernameExistsAsync(inValue);
        }
    }
}
