//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServicioReporte {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Servicios/", ConfigurationName="ServicioReporte.ServicioReporte")]
    public interface ServicioReporte {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioReporte/getReporteMRequest", ReplyAction="http://Servicios/ServicioReporte/getReporteMResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaGUI.ServicioReporte.getReporteMResponse getReporteM(CapaGUI.ServicioReporte.getReporteMRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioReporte/getReporteMRequest", ReplyAction="http://Servicios/ServicioReporte/getReporteMResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioReporte.getReporteMResponse> getReporteMAsync(CapaGUI.ServicioReporte.getReporteMRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioReporte/reporteGananciaZonaRequest", ReplyAction="http://Servicios/ServicioReporte/reporteGananciaZonaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaGUI.ServicioReporte.reporteGananciaZonaResponse reporteGananciaZona(CapaGUI.ServicioReporte.reporteGananciaZonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioReporte/reporteGananciaZonaRequest", ReplyAction="http://Servicios/ServicioReporte/reporteGananciaZonaResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioReporte.reporteGananciaZonaResponse> reporteGananciaZonaAsync(CapaGUI.ServicioReporte.reporteGananciaZonaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioReporte/getReporteGananciaMensualRequest", ReplyAction="http://Servicios/ServicioReporte/getReporteGananciaMensualResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaGUI.ServicioReporte.getReporteGananciaMensualResponse getReporteGananciaMensual(CapaGUI.ServicioReporte.getReporteGananciaMensualRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioReporte/getReporteGananciaMensualRequest", ReplyAction="http://Servicios/ServicioReporte/getReporteGananciaMensualResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioReporte.getReporteGananciaMensualResponse> getReporteGananciaMensualAsync(CapaGUI.ServicioReporte.getReporteGananciaMensualRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioReporte/reporteGananciaMensualZonaRequest", ReplyAction="http://Servicios/ServicioReporte/reporteGananciaMensualZonaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaGUI.ServicioReporte.reporteGananciaMensualZonaResponse reporteGananciaMensualZona(CapaGUI.ServicioReporte.reporteGananciaMensualZonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioReporte/reporteGananciaMensualZonaRequest", ReplyAction="http://Servicios/ServicioReporte/reporteGananciaMensualZonaResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioReporte.reporteGananciaMensualZonaResponse> reporteGananciaMensualZonaAsync(CapaGUI.ServicioReporte.reporteGananciaMensualZonaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioReporte/getReporteGananciaRequest", ReplyAction="http://Servicios/ServicioReporte/getReporteGananciaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaGUI.ServicioReporte.getReporteGananciaResponse getReporteGanancia(CapaGUI.ServicioReporte.getReporteGananciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioReporte/getReporteGananciaRequest", ReplyAction="http://Servicios/ServicioReporte/getReporteGananciaResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioReporte.getReporteGananciaResponse> getReporteGananciaAsync(CapaGUI.ServicioReporte.getReporteGananciaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioReporte/reporteGananciaDiariaRequest", ReplyAction="http://Servicios/ServicioReporte/reporteGananciaDiariaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaGUI.ServicioReporte.reporteGananciaDiariaResponse reporteGananciaDiaria(CapaGUI.ServicioReporte.reporteGananciaDiariaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioReporte/reporteGananciaDiariaRequest", ReplyAction="http://Servicios/ServicioReporte/reporteGananciaDiariaResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioReporte.reporteGananciaDiariaResponse> reporteGananciaDiariaAsync(CapaGUI.ServicioReporte.reporteGananciaDiariaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioReporte/reporteGananciaDiariaZonaRequest", ReplyAction="http://Servicios/ServicioReporte/reporteGananciaDiariaZonaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaGUI.ServicioReporte.reporteGananciaDiariaZonaResponse reporteGananciaDiariaZona(CapaGUI.ServicioReporte.reporteGananciaDiariaZonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioReporte/reporteGananciaDiariaZonaRequest", ReplyAction="http://Servicios/ServicioReporte/reporteGananciaDiariaZonaResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioReporte.reporteGananciaDiariaZonaResponse> reporteGananciaDiariaZonaAsync(CapaGUI.ServicioReporte.reporteGananciaDiariaZonaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class reporteMensualReservas : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int arriendosField;
        
        private string mesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int arriendos {
            get {
                return this.arriendosField;
            }
            set {
                this.arriendosField = value;
                this.RaisePropertyChanged("arriendos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mes {
            get {
                return this.mesField;
            }
            set {
                this.mesField = value;
                this.RaisePropertyChanged("mes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class reporteGanancia : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string direccionField;
        
        private int gananciaField;
        
        private int idDeptoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int ganancia {
            get {
                return this.gananciaField;
            }
            set {
                this.gananciaField = value;
                this.RaisePropertyChanged("ganancia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idDepto {
            get {
                return this.idDeptoField;
            }
            set {
                this.idDeptoField = value;
                this.RaisePropertyChanged("idDepto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class reporteZona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int gananciaField;
        
        private string regionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int ganancia {
            get {
                return this.gananciaField;
            }
            set {
                this.gananciaField = value;
                this.RaisePropertyChanged("ganancia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
                this.RaisePropertyChanged("region");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReporteM", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class getReporteMRequest {
        
        public getReporteMRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReporteMResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class getReporteMResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CapaGUI.ServicioReporte.reporteMensualReservas[] @return;
        
        public getReporteMResponse() {
        }
        
        public getReporteMResponse(CapaGUI.ServicioReporte.reporteMensualReservas[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reporteGananciaZona", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class reporteGananciaZonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int intAno;
        
        public reporteGananciaZonaRequest() {
        }
        
        public reporteGananciaZonaRequest(int intAno) {
            this.intAno = intAno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reporteGananciaZonaResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class reporteGananciaZonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CapaGUI.ServicioReporte.reporteZona[] @return;
        
        public reporteGananciaZonaResponse() {
        }
        
        public reporteGananciaZonaResponse(CapaGUI.ServicioReporte.reporteZona[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReporteGananciaMensual", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class getReporteGananciaMensualRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int intMes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int intAno;
        
        public getReporteGananciaMensualRequest() {
        }
        
        public getReporteGananciaMensualRequest(int intMes, int intAno) {
            this.intMes = intMes;
            this.intAno = intAno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReporteGananciaMensualResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class getReporteGananciaMensualResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CapaGUI.ServicioReporte.reporteGanancia[] @return;
        
        public getReporteGananciaMensualResponse() {
        }
        
        public getReporteGananciaMensualResponse(CapaGUI.ServicioReporte.reporteGanancia[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reporteGananciaMensualZona", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class reporteGananciaMensualZonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int intMes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int intAno;
        
        public reporteGananciaMensualZonaRequest() {
        }
        
        public reporteGananciaMensualZonaRequest(int intMes, int intAno) {
            this.intMes = intMes;
            this.intAno = intAno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reporteGananciaMensualZonaResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class reporteGananciaMensualZonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CapaGUI.ServicioReporte.reporteZona[] @return;
        
        public reporteGananciaMensualZonaResponse() {
        }
        
        public reporteGananciaMensualZonaResponse(CapaGUI.ServicioReporte.reporteZona[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReporteGanancia", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class getReporteGananciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int intAno;
        
        public getReporteGananciaRequest() {
        }
        
        public getReporteGananciaRequest(int intAno) {
            this.intAno = intAno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getReporteGananciaResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class getReporteGananciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CapaGUI.ServicioReporte.reporteGanancia[] @return;
        
        public getReporteGananciaResponse() {
        }
        
        public getReporteGananciaResponse(CapaGUI.ServicioReporte.reporteGanancia[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reporteGananciaDiaria", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class reporteGananciaDiariaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int intDia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int intMes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int intAno;
        
        public reporteGananciaDiariaRequest() {
        }
        
        public reporteGananciaDiariaRequest(int intDia, int intMes, int intAno) {
            this.intDia = intDia;
            this.intMes = intMes;
            this.intAno = intAno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reporteGananciaDiariaResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class reporteGananciaDiariaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CapaGUI.ServicioReporte.reporteGanancia[] @return;
        
        public reporteGananciaDiariaResponse() {
        }
        
        public reporteGananciaDiariaResponse(CapaGUI.ServicioReporte.reporteGanancia[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reporteGananciaDiariaZona", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class reporteGananciaDiariaZonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int intDia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int intMes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int intAno;
        
        public reporteGananciaDiariaZonaRequest() {
        }
        
        public reporteGananciaDiariaZonaRequest(int intDia, int intMes, int intAno) {
            this.intDia = intDia;
            this.intMes = intMes;
            this.intAno = intAno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reporteGananciaDiariaZonaResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class reporteGananciaDiariaZonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CapaGUI.ServicioReporte.reporteZona[] @return;
        
        public reporteGananciaDiariaZonaResponse() {
        }
        
        public reporteGananciaDiariaZonaResponse(CapaGUI.ServicioReporte.reporteZona[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioReporteChannel : CapaGUI.ServicioReporte.ServicioReporte, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioReporteClient : System.ServiceModel.ClientBase<CapaGUI.ServicioReporte.ServicioReporte>, CapaGUI.ServicioReporte.ServicioReporte {
        
        public ServicioReporteClient() {
        }
        
        public ServicioReporteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioReporteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioReporteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioReporteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioReporte.getReporteMResponse CapaGUI.ServicioReporte.ServicioReporte.getReporteM(CapaGUI.ServicioReporte.getReporteMRequest request) {
            return base.Channel.getReporteM(request);
        }
        
        public CapaGUI.ServicioReporte.reporteMensualReservas[] getReporteM() {
            CapaGUI.ServicioReporte.getReporteMRequest inValue = new CapaGUI.ServicioReporte.getReporteMRequest();
            CapaGUI.ServicioReporte.getReporteMResponse retVal = ((CapaGUI.ServicioReporte.ServicioReporte)(this)).getReporteM(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioReporte.getReporteMResponse> CapaGUI.ServicioReporte.ServicioReporte.getReporteMAsync(CapaGUI.ServicioReporte.getReporteMRequest request) {
            return base.Channel.getReporteMAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioReporte.getReporteMResponse> getReporteMAsync() {
            CapaGUI.ServicioReporte.getReporteMRequest inValue = new CapaGUI.ServicioReporte.getReporteMRequest();
            return ((CapaGUI.ServicioReporte.ServicioReporte)(this)).getReporteMAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioReporte.reporteGananciaZonaResponse CapaGUI.ServicioReporte.ServicioReporte.reporteGananciaZona(CapaGUI.ServicioReporte.reporteGananciaZonaRequest request) {
            return base.Channel.reporteGananciaZona(request);
        }
        
        public CapaGUI.ServicioReporte.reporteZona[] reporteGananciaZona(int intAno) {
            CapaGUI.ServicioReporte.reporteGananciaZonaRequest inValue = new CapaGUI.ServicioReporte.reporteGananciaZonaRequest();
            inValue.intAno = intAno;
            CapaGUI.ServicioReporte.reporteGananciaZonaResponse retVal = ((CapaGUI.ServicioReporte.ServicioReporte)(this)).reporteGananciaZona(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioReporte.reporteGananciaZonaResponse> CapaGUI.ServicioReporte.ServicioReporte.reporteGananciaZonaAsync(CapaGUI.ServicioReporte.reporteGananciaZonaRequest request) {
            return base.Channel.reporteGananciaZonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioReporte.reporteGananciaZonaResponse> reporteGananciaZonaAsync(int intAno) {
            CapaGUI.ServicioReporte.reporteGananciaZonaRequest inValue = new CapaGUI.ServicioReporte.reporteGananciaZonaRequest();
            inValue.intAno = intAno;
            return ((CapaGUI.ServicioReporte.ServicioReporte)(this)).reporteGananciaZonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioReporte.getReporteGananciaMensualResponse CapaGUI.ServicioReporte.ServicioReporte.getReporteGananciaMensual(CapaGUI.ServicioReporte.getReporteGananciaMensualRequest request) {
            return base.Channel.getReporteGananciaMensual(request);
        }
        
        public CapaGUI.ServicioReporte.reporteGanancia[] getReporteGananciaMensual(int intMes, int intAno) {
            CapaGUI.ServicioReporte.getReporteGananciaMensualRequest inValue = new CapaGUI.ServicioReporte.getReporteGananciaMensualRequest();
            inValue.intMes = intMes;
            inValue.intAno = intAno;
            CapaGUI.ServicioReporte.getReporteGananciaMensualResponse retVal = ((CapaGUI.ServicioReporte.ServicioReporte)(this)).getReporteGananciaMensual(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioReporte.getReporteGananciaMensualResponse> CapaGUI.ServicioReporte.ServicioReporte.getReporteGananciaMensualAsync(CapaGUI.ServicioReporte.getReporteGananciaMensualRequest request) {
            return base.Channel.getReporteGananciaMensualAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioReporte.getReporteGananciaMensualResponse> getReporteGananciaMensualAsync(int intMes, int intAno) {
            CapaGUI.ServicioReporte.getReporteGananciaMensualRequest inValue = new CapaGUI.ServicioReporte.getReporteGananciaMensualRequest();
            inValue.intMes = intMes;
            inValue.intAno = intAno;
            return ((CapaGUI.ServicioReporte.ServicioReporte)(this)).getReporteGananciaMensualAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioReporte.reporteGananciaMensualZonaResponse CapaGUI.ServicioReporte.ServicioReporte.reporteGananciaMensualZona(CapaGUI.ServicioReporte.reporteGananciaMensualZonaRequest request) {
            return base.Channel.reporteGananciaMensualZona(request);
        }
        
        public CapaGUI.ServicioReporte.reporteZona[] reporteGananciaMensualZona(int intMes, int intAno) {
            CapaGUI.ServicioReporte.reporteGananciaMensualZonaRequest inValue = new CapaGUI.ServicioReporte.reporteGananciaMensualZonaRequest();
            inValue.intMes = intMes;
            inValue.intAno = intAno;
            CapaGUI.ServicioReporte.reporteGananciaMensualZonaResponse retVal = ((CapaGUI.ServicioReporte.ServicioReporte)(this)).reporteGananciaMensualZona(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioReporte.reporteGananciaMensualZonaResponse> CapaGUI.ServicioReporte.ServicioReporte.reporteGananciaMensualZonaAsync(CapaGUI.ServicioReporte.reporteGananciaMensualZonaRequest request) {
            return base.Channel.reporteGananciaMensualZonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioReporte.reporteGananciaMensualZonaResponse> reporteGananciaMensualZonaAsync(int intMes, int intAno) {
            CapaGUI.ServicioReporte.reporteGananciaMensualZonaRequest inValue = new CapaGUI.ServicioReporte.reporteGananciaMensualZonaRequest();
            inValue.intMes = intMes;
            inValue.intAno = intAno;
            return ((CapaGUI.ServicioReporte.ServicioReporte)(this)).reporteGananciaMensualZonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioReporte.getReporteGananciaResponse CapaGUI.ServicioReporte.ServicioReporte.getReporteGanancia(CapaGUI.ServicioReporte.getReporteGananciaRequest request) {
            return base.Channel.getReporteGanancia(request);
        }
        
        public CapaGUI.ServicioReporte.reporteGanancia[] getReporteGanancia(int intAno) {
            CapaGUI.ServicioReporte.getReporteGananciaRequest inValue = new CapaGUI.ServicioReporte.getReporteGananciaRequest();
            inValue.intAno = intAno;
            CapaGUI.ServicioReporte.getReporteGananciaResponse retVal = ((CapaGUI.ServicioReporte.ServicioReporte)(this)).getReporteGanancia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioReporte.getReporteGananciaResponse> CapaGUI.ServicioReporte.ServicioReporte.getReporteGananciaAsync(CapaGUI.ServicioReporte.getReporteGananciaRequest request) {
            return base.Channel.getReporteGananciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioReporte.getReporteGananciaResponse> getReporteGananciaAsync(int intAno) {
            CapaGUI.ServicioReporte.getReporteGananciaRequest inValue = new CapaGUI.ServicioReporte.getReporteGananciaRequest();
            inValue.intAno = intAno;
            return ((CapaGUI.ServicioReporte.ServicioReporte)(this)).getReporteGananciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioReporte.reporteGananciaDiariaResponse CapaGUI.ServicioReporte.ServicioReporte.reporteGananciaDiaria(CapaGUI.ServicioReporte.reporteGananciaDiariaRequest request) {
            return base.Channel.reporteGananciaDiaria(request);
        }
        
        public CapaGUI.ServicioReporte.reporteGanancia[] reporteGananciaDiaria(int intDia, int intMes, int intAno) {
            CapaGUI.ServicioReporte.reporteGananciaDiariaRequest inValue = new CapaGUI.ServicioReporte.reporteGananciaDiariaRequest();
            inValue.intDia = intDia;
            inValue.intMes = intMes;
            inValue.intAno = intAno;
            CapaGUI.ServicioReporte.reporteGananciaDiariaResponse retVal = ((CapaGUI.ServicioReporte.ServicioReporte)(this)).reporteGananciaDiaria(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioReporte.reporteGananciaDiariaResponse> CapaGUI.ServicioReporte.ServicioReporte.reporteGananciaDiariaAsync(CapaGUI.ServicioReporte.reporteGananciaDiariaRequest request) {
            return base.Channel.reporteGananciaDiariaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioReporte.reporteGananciaDiariaResponse> reporteGananciaDiariaAsync(int intDia, int intMes, int intAno) {
            CapaGUI.ServicioReporte.reporteGananciaDiariaRequest inValue = new CapaGUI.ServicioReporte.reporteGananciaDiariaRequest();
            inValue.intDia = intDia;
            inValue.intMes = intMes;
            inValue.intAno = intAno;
            return ((CapaGUI.ServicioReporte.ServicioReporte)(this)).reporteGananciaDiariaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioReporte.reporteGananciaDiariaZonaResponse CapaGUI.ServicioReporte.ServicioReporte.reporteGananciaDiariaZona(CapaGUI.ServicioReporte.reporteGananciaDiariaZonaRequest request) {
            return base.Channel.reporteGananciaDiariaZona(request);
        }
        
        public CapaGUI.ServicioReporte.reporteZona[] reporteGananciaDiariaZona(int intDia, int intMes, int intAno) {
            CapaGUI.ServicioReporte.reporteGananciaDiariaZonaRequest inValue = new CapaGUI.ServicioReporte.reporteGananciaDiariaZonaRequest();
            inValue.intDia = intDia;
            inValue.intMes = intMes;
            inValue.intAno = intAno;
            CapaGUI.ServicioReporte.reporteGananciaDiariaZonaResponse retVal = ((CapaGUI.ServicioReporte.ServicioReporte)(this)).reporteGananciaDiariaZona(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioReporte.reporteGananciaDiariaZonaResponse> CapaGUI.ServicioReporte.ServicioReporte.reporteGananciaDiariaZonaAsync(CapaGUI.ServicioReporte.reporteGananciaDiariaZonaRequest request) {
            return base.Channel.reporteGananciaDiariaZonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioReporte.reporteGananciaDiariaZonaResponse> reporteGananciaDiariaZonaAsync(int intDia, int intMes, int intAno) {
            CapaGUI.ServicioReporte.reporteGananciaDiariaZonaRequest inValue = new CapaGUI.ServicioReporte.reporteGananciaDiariaZonaRequest();
            inValue.intDia = intDia;
            inValue.intMes = intMes;
            inValue.intAno = intAno;
            return ((CapaGUI.ServicioReporte.ServicioReporte)(this)).reporteGananciaDiariaZonaAsync(inValue);
        }
    }
}
