//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServicioDepto {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Servicios/", ConfigurationName="ServicioDepto.ServicioDepartamento")]
    public interface ServicioDepartamento {
        
        // CODEGEN: El parámetro 'idDepto' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioDepartamento/ActualizarDeptoRequest", ReplyAction="http://Servicios/ServicioDepartamento/ActualizarDeptoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUI.ServicioDepto.ActualizarDeptoResponse ActualizarDepto(CapaGUI.ServicioDepto.ActualizarDeptoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioDepartamento/ActualizarDeptoRequest", ReplyAction="http://Servicios/ServicioDepartamento/ActualizarDeptoResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioDepto.ActualizarDeptoResponse> ActualizarDeptoAsync(CapaGUI.ServicioDepto.ActualizarDeptoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioDepartamento/CancelarRegistroRequest", ReplyAction="http://Servicios/ServicioDepartamento/CancelarRegistroResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaGUI.ServicioDepto.CancelarRegistroResponse CancelarRegistro(CapaGUI.ServicioDepto.CancelarRegistroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioDepartamento/CancelarRegistroRequest", ReplyAction="http://Servicios/ServicioDepartamento/CancelarRegistroResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioDepto.CancelarRegistroResponse> CancelarRegistroAsync(CapaGUI.ServicioDepto.CancelarRegistroRequest request);
        
        // CODEGEN: El parámetro 'idDepto' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioDepartamento/EliminarDeptoRequest", ReplyAction="http://Servicios/ServicioDepartamento/EliminarDeptoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUI.ServicioDepto.EliminarDeptoResponse EliminarDepto(CapaGUI.ServicioDepto.EliminarDeptoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioDepartamento/EliminarDeptoRequest", ReplyAction="http://Servicios/ServicioDepartamento/EliminarDeptoResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioDepto.EliminarDeptoResponse> EliminarDeptoAsync(CapaGUI.ServicioDepto.EliminarDeptoRequest request);
        
        // CODEGEN: El parámetro 'direccion' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioDepartamento/IngresarDeptoRequest", ReplyAction="http://Servicios/ServicioDepartamento/IngresarDeptoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUI.ServicioDepto.IngresarDeptoResponse IngresarDepto(CapaGUI.ServicioDepto.IngresarDeptoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioDepartamento/IngresarDeptoRequest", ReplyAction="http://Servicios/ServicioDepartamento/IngresarDeptoResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioDepto.IngresarDeptoResponse> IngresarDeptoAsync(CapaGUI.ServicioDepto.IngresarDeptoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioDepartamento/ListarDeptoRequest", ReplyAction="http://Servicios/ServicioDepartamento/ListarDeptoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaGUI.ServicioDepto.ListarDeptoResponse ListarDepto(CapaGUI.ServicioDepto.ListarDeptoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioDepartamento/ListarDeptoRequest", ReplyAction="http://Servicios/ServicioDepartamento/ListarDeptoResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioDepto.ListarDeptoResponse> ListarDeptoAsync(CapaGUI.ServicioDepto.ListarDeptoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarDepto", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class ActualizarDeptoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idDepto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadPiezas;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadBanos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string condiciones;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTipoEstado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idComuna;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTarifa;
        
        public ActualizarDeptoRequest() {
        }
        
        public ActualizarDeptoRequest(int idDepto, string direccion, int cantidadPiezas, int cantidadBanos, string condiciones, int idTipoEstado, int idComuna, int idTarifa) {
            this.idDepto = idDepto;
            this.direccion = direccion;
            this.cantidadPiezas = cantidadPiezas;
            this.cantidadBanos = cantidadBanos;
            this.condiciones = condiciones;
            this.idTipoEstado = idTipoEstado;
            this.idComuna = idComuna;
            this.idTarifa = idTarifa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarDeptoResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class ActualizarDeptoResponse {
        
        public ActualizarDeptoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelarRegistro", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class CancelarRegistroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idReserva;
        
        public CancelarRegistroRequest() {
        }
        
        public CancelarRegistroRequest(int idReserva) {
            this.idReserva = idReserva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CancelarRegistroResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class CancelarRegistroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public CancelarRegistroResponse() {
        }
        
        public CancelarRegistroResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarDepto", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class EliminarDeptoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idDepto;
        
        public EliminarDeptoRequest() {
        }
        
        public EliminarDeptoRequest(int idDepto) {
            this.idDepto = idDepto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EliminarDeptoResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class EliminarDeptoResponse {
        
        public EliminarDeptoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IngresarDepto", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class IngresarDeptoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadPiezas;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadBanos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string condiciones;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTipoEstado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idComuna;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTarifa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string V_PATH;
        
        public IngresarDeptoRequest() {
        }
        
        public IngresarDeptoRequest(string direccion, int cantidadPiezas, int cantidadBanos, string condiciones, int idTipoEstado, int idComuna, int idTarifa, string V_PATH) {
            this.direccion = direccion;
            this.cantidadPiezas = cantidadPiezas;
            this.cantidadBanos = cantidadBanos;
            this.condiciones = condiciones;
            this.idTipoEstado = idTipoEstado;
            this.idComuna = idComuna;
            this.idTarifa = idTarifa;
            this.V_PATH = V_PATH;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IngresarDeptoResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class IngresarDeptoResponse {
        
        public IngresarDeptoResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class listaDepto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantidadBanosField;
        
        private int cantidadPiezasField;
        
        private string comunaField;
        
        private string condicionesField;
        
        private string direccionField;
        
        private int idDepartamentoField;
        
        private int idEstadoField;
        
        private byte[] imageField;
        
        private int tarifaField;
        
        private string tipoEstadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidadBanos {
            get {
                return this.cantidadBanosField;
            }
            set {
                this.cantidadBanosField = value;
                this.RaisePropertyChanged("cantidadBanos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int cantidadPiezas {
            get {
                return this.cantidadPiezasField;
            }
            set {
                this.cantidadPiezasField = value;
                this.RaisePropertyChanged("cantidadPiezas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string comuna {
            get {
                return this.comunaField;
            }
            set {
                this.comunaField = value;
                this.RaisePropertyChanged("comuna");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string condiciones {
            get {
                return this.condicionesField;
            }
            set {
                this.condicionesField = value;
                this.RaisePropertyChanged("condiciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idDepartamento {
            get {
                return this.idDepartamentoField;
            }
            set {
                this.idDepartamentoField = value;
                this.RaisePropertyChanged("idDepartamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int idEstado {
            get {
                return this.idEstadoField;
            }
            set {
                this.idEstadoField = value;
                this.RaisePropertyChanged("idEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=7)]
        public byte[] image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
                this.RaisePropertyChanged("image");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int tarifa {
            get {
                return this.tarifaField;
            }
            set {
                this.tarifaField = value;
                this.RaisePropertyChanged("tarifa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string tipoEstado {
            get {
                return this.tipoEstadoField;
            }
            set {
                this.tipoEstadoField = value;
                this.RaisePropertyChanged("tipoEstado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarDepto", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class ListarDeptoRequest {
        
        public ListarDeptoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListarDeptoResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class ListarDeptoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CapaGUI.ServicioDepto.listaDepto[] @return;
        
        public ListarDeptoResponse() {
        }
        
        public ListarDeptoResponse(CapaGUI.ServicioDepto.listaDepto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioDepartamentoChannel : CapaGUI.ServicioDepto.ServicioDepartamento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioDepartamentoClient : System.ServiceModel.ClientBase<CapaGUI.ServicioDepto.ServicioDepartamento>, CapaGUI.ServicioDepto.ServicioDepartamento {
        
        public ServicioDepartamentoClient() {
        }
        
        public ServicioDepartamentoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioDepartamentoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioDepartamentoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioDepartamentoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioDepto.ActualizarDeptoResponse CapaGUI.ServicioDepto.ServicioDepartamento.ActualizarDepto(CapaGUI.ServicioDepto.ActualizarDeptoRequest request) {
            return base.Channel.ActualizarDepto(request);
        }
        
        public void ActualizarDepto(int idDepto, string direccion, int cantidadPiezas, int cantidadBanos, string condiciones, int idTipoEstado, int idComuna, int idTarifa) {
            CapaGUI.ServicioDepto.ActualizarDeptoRequest inValue = new CapaGUI.ServicioDepto.ActualizarDeptoRequest();
            inValue.idDepto = idDepto;
            inValue.direccion = direccion;
            inValue.cantidadPiezas = cantidadPiezas;
            inValue.cantidadBanos = cantidadBanos;
            inValue.condiciones = condiciones;
            inValue.idTipoEstado = idTipoEstado;
            inValue.idComuna = idComuna;
            inValue.idTarifa = idTarifa;
            CapaGUI.ServicioDepto.ActualizarDeptoResponse retVal = ((CapaGUI.ServicioDepto.ServicioDepartamento)(this)).ActualizarDepto(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioDepto.ActualizarDeptoResponse> CapaGUI.ServicioDepto.ServicioDepartamento.ActualizarDeptoAsync(CapaGUI.ServicioDepto.ActualizarDeptoRequest request) {
            return base.Channel.ActualizarDeptoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioDepto.ActualizarDeptoResponse> ActualizarDeptoAsync(int idDepto, string direccion, int cantidadPiezas, int cantidadBanos, string condiciones, int idTipoEstado, int idComuna, int idTarifa) {
            CapaGUI.ServicioDepto.ActualizarDeptoRequest inValue = new CapaGUI.ServicioDepto.ActualizarDeptoRequest();
            inValue.idDepto = idDepto;
            inValue.direccion = direccion;
            inValue.cantidadPiezas = cantidadPiezas;
            inValue.cantidadBanos = cantidadBanos;
            inValue.condiciones = condiciones;
            inValue.idTipoEstado = idTipoEstado;
            inValue.idComuna = idComuna;
            inValue.idTarifa = idTarifa;
            return ((CapaGUI.ServicioDepto.ServicioDepartamento)(this)).ActualizarDeptoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioDepto.CancelarRegistroResponse CapaGUI.ServicioDepto.ServicioDepartamento.CancelarRegistro(CapaGUI.ServicioDepto.CancelarRegistroRequest request) {
            return base.Channel.CancelarRegistro(request);
        }
        
        public int CancelarRegistro(int idReserva) {
            CapaGUI.ServicioDepto.CancelarRegistroRequest inValue = new CapaGUI.ServicioDepto.CancelarRegistroRequest();
            inValue.idReserva = idReserva;
            CapaGUI.ServicioDepto.CancelarRegistroResponse retVal = ((CapaGUI.ServicioDepto.ServicioDepartamento)(this)).CancelarRegistro(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioDepto.CancelarRegistroResponse> CapaGUI.ServicioDepto.ServicioDepartamento.CancelarRegistroAsync(CapaGUI.ServicioDepto.CancelarRegistroRequest request) {
            return base.Channel.CancelarRegistroAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioDepto.CancelarRegistroResponse> CancelarRegistroAsync(int idReserva) {
            CapaGUI.ServicioDepto.CancelarRegistroRequest inValue = new CapaGUI.ServicioDepto.CancelarRegistroRequest();
            inValue.idReserva = idReserva;
            return ((CapaGUI.ServicioDepto.ServicioDepartamento)(this)).CancelarRegistroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioDepto.EliminarDeptoResponse CapaGUI.ServicioDepto.ServicioDepartamento.EliminarDepto(CapaGUI.ServicioDepto.EliminarDeptoRequest request) {
            return base.Channel.EliminarDepto(request);
        }
        
        public void EliminarDepto(int idDepto) {
            CapaGUI.ServicioDepto.EliminarDeptoRequest inValue = new CapaGUI.ServicioDepto.EliminarDeptoRequest();
            inValue.idDepto = idDepto;
            CapaGUI.ServicioDepto.EliminarDeptoResponse retVal = ((CapaGUI.ServicioDepto.ServicioDepartamento)(this)).EliminarDepto(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioDepto.EliminarDeptoResponse> CapaGUI.ServicioDepto.ServicioDepartamento.EliminarDeptoAsync(CapaGUI.ServicioDepto.EliminarDeptoRequest request) {
            return base.Channel.EliminarDeptoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioDepto.EliminarDeptoResponse> EliminarDeptoAsync(int idDepto) {
            CapaGUI.ServicioDepto.EliminarDeptoRequest inValue = new CapaGUI.ServicioDepto.EliminarDeptoRequest();
            inValue.idDepto = idDepto;
            return ((CapaGUI.ServicioDepto.ServicioDepartamento)(this)).EliminarDeptoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioDepto.IngresarDeptoResponse CapaGUI.ServicioDepto.ServicioDepartamento.IngresarDepto(CapaGUI.ServicioDepto.IngresarDeptoRequest request) {
            return base.Channel.IngresarDepto(request);
        }
        
        public void IngresarDepto(string direccion, int cantidadPiezas, int cantidadBanos, string condiciones, int idTipoEstado, int idComuna, int idTarifa, string V_PATH) {
            CapaGUI.ServicioDepto.IngresarDeptoRequest inValue = new CapaGUI.ServicioDepto.IngresarDeptoRequest();
            inValue.direccion = direccion;
            inValue.cantidadPiezas = cantidadPiezas;
            inValue.cantidadBanos = cantidadBanos;
            inValue.condiciones = condiciones;
            inValue.idTipoEstado = idTipoEstado;
            inValue.idComuna = idComuna;
            inValue.idTarifa = idTarifa;
            inValue.V_PATH = V_PATH;
            CapaGUI.ServicioDepto.IngresarDeptoResponse retVal = ((CapaGUI.ServicioDepto.ServicioDepartamento)(this)).IngresarDepto(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioDepto.IngresarDeptoResponse> CapaGUI.ServicioDepto.ServicioDepartamento.IngresarDeptoAsync(CapaGUI.ServicioDepto.IngresarDeptoRequest request) {
            return base.Channel.IngresarDeptoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioDepto.IngresarDeptoResponse> IngresarDeptoAsync(string direccion, int cantidadPiezas, int cantidadBanos, string condiciones, int idTipoEstado, int idComuna, int idTarifa, string V_PATH) {
            CapaGUI.ServicioDepto.IngresarDeptoRequest inValue = new CapaGUI.ServicioDepto.IngresarDeptoRequest();
            inValue.direccion = direccion;
            inValue.cantidadPiezas = cantidadPiezas;
            inValue.cantidadBanos = cantidadBanos;
            inValue.condiciones = condiciones;
            inValue.idTipoEstado = idTipoEstado;
            inValue.idComuna = idComuna;
            inValue.idTarifa = idTarifa;
            inValue.V_PATH = V_PATH;
            return ((CapaGUI.ServicioDepto.ServicioDepartamento)(this)).IngresarDeptoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioDepto.ListarDeptoResponse CapaGUI.ServicioDepto.ServicioDepartamento.ListarDepto(CapaGUI.ServicioDepto.ListarDeptoRequest request) {
            return base.Channel.ListarDepto(request);
        }
        
        public CapaGUI.ServicioDepto.listaDepto[] ListarDepto() {
            CapaGUI.ServicioDepto.ListarDeptoRequest inValue = new CapaGUI.ServicioDepto.ListarDeptoRequest();
            CapaGUI.ServicioDepto.ListarDeptoResponse retVal = ((CapaGUI.ServicioDepto.ServicioDepartamento)(this)).ListarDepto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioDepto.ListarDeptoResponse> CapaGUI.ServicioDepto.ServicioDepartamento.ListarDeptoAsync(CapaGUI.ServicioDepto.ListarDeptoRequest request) {
            return base.Channel.ListarDeptoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioDepto.ListarDeptoResponse> ListarDeptoAsync() {
            CapaGUI.ServicioDepto.ListarDeptoRequest inValue = new CapaGUI.ServicioDepto.ListarDeptoRequest();
            return ((CapaGUI.ServicioDepto.ServicioDepartamento)(this)).ListarDeptoAsync(inValue);
        }
    }
}
