//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServicioReserva {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Servicios/", ConfigurationName="ServicioReserva.ServicioReserva")]
    public interface ServicioReserva {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioReserva/reservaUsuario2Request", ReplyAction="http://Servicios/ServicioReserva/reservaUsuario2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaGUI.ServicioReserva.reservaUsuario2Response reservaUsuario2(CapaGUI.ServicioReserva.reservaUsuario2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioReserva/reservaUsuario2Request", ReplyAction="http://Servicios/ServicioReserva/reservaUsuario2Response")]
        System.Threading.Tasks.Task<CapaGUI.ServicioReserva.reservaUsuario2Response> reservaUsuario2Async(CapaGUI.ServicioReserva.reservaUsuario2Request request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioReserva/consultaReservasRequest", ReplyAction="http://Servicios/ServicioReserva/consultaReservasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaGUI.ServicioReserva.consultaReservasResponse consultaReservas(CapaGUI.ServicioReserva.consultaReservasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioReserva/consultaReservasRequest", ReplyAction="http://Servicios/ServicioReserva/consultaReservasResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioReserva.consultaReservasResponse> consultaReservasAsync(CapaGUI.ServicioReserva.consultaReservasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioReserva/listarReservaRequest", ReplyAction="http://Servicios/ServicioReserva/listarReservaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaGUI.ServicioReserva.listarReservaResponse listarReserva(CapaGUI.ServicioReserva.listarReservaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioReserva/listarReservaRequest", ReplyAction="http://Servicios/ServicioReserva/listarReservaResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioReserva.listarReservaResponse> listarReservaAsync(CapaGUI.ServicioReserva.listarReservaRequest request);
        
        // CODEGEN: El parámetro 'fechaInicio' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioReserva/insertReservaRequest", ReplyAction="http://Servicios/ServicioReserva/insertReservaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUI.ServicioReserva.insertReservaResponse insertReserva(CapaGUI.ServicioReserva.insertReservaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioReserva/insertReservaRequest", ReplyAction="http://Servicios/ServicioReserva/insertReservaResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioReserva.insertReservaResponse> insertReservaAsync(CapaGUI.ServicioReserva.insertReservaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioReserva/GetTurismoByReservaRequest", ReplyAction="http://Servicios/ServicioReserva/GetTurismoByReservaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaGUI.ServicioReserva.GetTurismoByReservaResponse GetTurismoByReserva(CapaGUI.ServicioReserva.GetTurismoByReservaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioReserva/GetTurismoByReservaRequest", ReplyAction="http://Servicios/ServicioReserva/GetTurismoByReservaResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioReserva.GetTurismoByReservaResponse> GetTurismoByReservaAsync(CapaGUI.ServicioReserva.GetTurismoByReservaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioReserva/consultaReservasOutRequest", ReplyAction="http://Servicios/ServicioReserva/consultaReservasOutResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaGUI.ServicioReserva.consultaReservasOutResponse consultaReservasOut(CapaGUI.ServicioReserva.consultaReservasOutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioReserva/consultaReservasOutRequest", ReplyAction="http://Servicios/ServicioReserva/consultaReservasOutResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioReserva.consultaReservasOutResponse> consultaReservasOutAsync(CapaGUI.ServicioReserva.consultaReservasOutRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioReserva/GetTransporteByReservaRequest", ReplyAction="http://Servicios/ServicioReserva/GetTransporteByReservaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaGUI.ServicioReserva.GetTransporteByReservaResponse GetTransporteByReserva(CapaGUI.ServicioReserva.GetTransporteByReservaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioReserva/GetTransporteByReservaRequest", ReplyAction="http://Servicios/ServicioReserva/GetTransporteByReservaResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioReserva.GetTransporteByReservaResponse> GetTransporteByReservaAsync(CapaGUI.ServicioReserva.GetTransporteByReservaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioReserva/GetAcompaniantesByReservaRequest", ReplyAction="http://Servicios/ServicioReserva/GetAcompaniantesByReservaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaGUI.ServicioReserva.GetAcompaniantesByReservaResponse GetAcompaniantesByReserva(CapaGUI.ServicioReserva.GetAcompaniantesByReservaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioReserva/GetAcompaniantesByReservaRequest", ReplyAction="http://Servicios/ServicioReserva/GetAcompaniantesByReservaResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioReserva.GetAcompaniantesByReservaResponse> GetAcompaniantesByReservaAsync(CapaGUI.ServicioReserva.GetAcompaniantesByReservaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioReserva/validarFechaReservaRequest", ReplyAction="http://Servicios/ServicioReserva/validarFechaReservaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaGUI.ServicioReserva.validarFechaReservaResponse validarFechaReserva(CapaGUI.ServicioReserva.validarFechaReservaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioReserva/validarFechaReservaRequest", ReplyAction="http://Servicios/ServicioReserva/validarFechaReservaResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioReserva.validarFechaReservaResponse> validarFechaReservaAsync(CapaGUI.ServicioReserva.validarFechaReservaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class reservaUsuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string deptoField;
        
        private string fechaField;
        
        private string fechaFinField;
        
        private string fechaInicioField;
        
        private int idReservaField;
        
        private int pagoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string depto {
            get {
                return this.deptoField;
            }
            set {
                this.deptoField = value;
                this.RaisePropertyChanged("depto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idReserva {
            get {
                return this.idReservaField;
            }
            set {
                this.idReservaField = value;
                this.RaisePropertyChanged("idReserva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int pago {
            get {
                return this.pagoField;
            }
            set {
                this.pagoField = value;
                this.RaisePropertyChanged("pago");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class acompanianteReserva : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class servicioReservaList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private string fechaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class reservaDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fechaField;
        
        private string fechaFinField;
        
        private string fechaInicioField;
        
        private int idClienteField;
        
        private int idDptoField;
        
        private int idReservaField;
        
        private int pagoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idCliente {
            get {
                return this.idClienteField;
            }
            set {
                this.idClienteField = value;
                this.RaisePropertyChanged("idCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idDpto {
            get {
                return this.idDptoField;
            }
            set {
                this.idDptoField = value;
                this.RaisePropertyChanged("idDpto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idReserva {
            get {
                return this.idReservaField;
            }
            set {
                this.idReservaField = value;
                this.RaisePropertyChanged("idReserva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int pago {
            get {
                return this.pagoField;
            }
            set {
                this.pagoField = value;
                this.RaisePropertyChanged("pago");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class reserva : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fechaField;
        
        private string fecha_finField;
        
        private string fecha_inicioField;
        
        private int id_clienteField;
        
        private int id_departamentoField;
        
        private int id_reservaField;
        
        private int pagoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fecha_fin {
            get {
                return this.fecha_finField;
            }
            set {
                this.fecha_finField = value;
                this.RaisePropertyChanged("fecha_fin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string fecha_inicio {
            get {
                return this.fecha_inicioField;
            }
            set {
                this.fecha_inicioField = value;
                this.RaisePropertyChanged("fecha_inicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id_cliente {
            get {
                return this.id_clienteField;
            }
            set {
                this.id_clienteField = value;
                this.RaisePropertyChanged("id_cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int id_departamento {
            get {
                return this.id_departamentoField;
            }
            set {
                this.id_departamentoField = value;
                this.RaisePropertyChanged("id_departamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int id_reserva {
            get {
                return this.id_reservaField;
            }
            set {
                this.id_reservaField = value;
                this.RaisePropertyChanged("id_reserva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int pago {
            get {
                return this.pagoField;
            }
            set {
                this.pagoField = value;
                this.RaisePropertyChanged("pago");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reservaUsuario2", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class reservaUsuario2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreUsuario;
        
        public reservaUsuario2Request() {
        }
        
        public reservaUsuario2Request(string nombreUsuario) {
            this.nombreUsuario = nombreUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reservaUsuario2Response", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class reservaUsuario2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CapaGUI.ServicioReserva.reservaUsuario[] @return;
        
        public reservaUsuario2Response() {
        }
        
        public reservaUsuario2Response(CapaGUI.ServicioReserva.reservaUsuario[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaReservas", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class consultaReservasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idDepto;
        
        public consultaReservasRequest() {
        }
        
        public consultaReservasRequest(string idDepto) {
            this.idDepto = idDepto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaReservasResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class consultaReservasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CapaGUI.ServicioReserva.reserva[] @return;
        
        public consultaReservasResponse() {
        }
        
        public consultaReservasResponse(CapaGUI.ServicioReserva.reserva[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarReserva", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class listarReservaRequest {
        
        public listarReservaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarReservaResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class listarReservaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CapaGUI.ServicioReserva.reservaDto[] @return;
        
        public listarReservaResponse() {
        }
        
        public listarReservaResponse(CapaGUI.ServicioReserva.reservaDto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertReserva", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class insertReservaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaInicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaFin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int pago;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idDpto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCliente;
        
        public insertReservaRequest() {
        }
        
        public insertReservaRequest(string fechaInicio, string fechaFin, int pago, int idDpto, int idCliente) {
            this.fechaInicio = fechaInicio;
            this.fechaFin = fechaFin;
            this.pago = pago;
            this.idDpto = idDpto;
            this.idCliente = idCliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertReservaResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class insertReservaResponse {
        
        public insertReservaResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTurismoByReserva", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class GetTurismoByReservaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idReserva;
        
        public GetTurismoByReservaRequest() {
        }
        
        public GetTurismoByReservaRequest(int idReserva) {
            this.idReserva = idReserva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTurismoByReservaResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class GetTurismoByReservaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CapaGUI.ServicioReserva.servicioReservaList[] @return;
        
        public GetTurismoByReservaResponse() {
        }
        
        public GetTurismoByReservaResponse(CapaGUI.ServicioReserva.servicioReservaList[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaReservasOut", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class consultaReservasOutRequest {
        
        public consultaReservasOutRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaReservasOutResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class consultaReservasOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CapaGUI.ServicioReserva.reserva[] @return;
        
        public consultaReservasOutResponse() {
        }
        
        public consultaReservasOutResponse(CapaGUI.ServicioReserva.reserva[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTransporteByReserva", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class GetTransporteByReservaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idReserva;
        
        public GetTransporteByReservaRequest() {
        }
        
        public GetTransporteByReservaRequest(int idReserva) {
            this.idReserva = idReserva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTransporteByReservaResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class GetTransporteByReservaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CapaGUI.ServicioReserva.servicioReservaList[] @return;
        
        public GetTransporteByReservaResponse() {
        }
        
        public GetTransporteByReservaResponse(CapaGUI.ServicioReserva.servicioReservaList[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAcompaniantesByReserva", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class GetAcompaniantesByReservaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idReserva;
        
        public GetAcompaniantesByReservaRequest() {
        }
        
        public GetAcompaniantesByReservaRequest(int idReserva) {
            this.idReserva = idReserva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAcompaniantesByReservaResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class GetAcompaniantesByReservaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CapaGUI.ServicioReserva.acompanianteReserva[] @return;
        
        public GetAcompaniantesByReservaResponse() {
        }
        
        public GetAcompaniantesByReservaResponse(CapaGUI.ServicioReserva.acompanianteReserva[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validarFechaReserva", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class validarFechaReservaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idDepto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fecha_inicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fecha_fin;
        
        public validarFechaReservaRequest() {
        }
        
        public validarFechaReservaRequest(int idDepto, string fecha_inicio, string fecha_fin) {
            this.idDepto = idDepto;
            this.fecha_inicio = fecha_inicio;
            this.fecha_fin = fecha_fin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validarFechaReservaResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class validarFechaReservaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public validarFechaReservaResponse() {
        }
        
        public validarFechaReservaResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioReservaChannel : CapaGUI.ServicioReserva.ServicioReserva, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioReservaClient : System.ServiceModel.ClientBase<CapaGUI.ServicioReserva.ServicioReserva>, CapaGUI.ServicioReserva.ServicioReserva {
        
        public ServicioReservaClient() {
        }
        
        public ServicioReservaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioReservaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioReservaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioReservaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioReserva.reservaUsuario2Response CapaGUI.ServicioReserva.ServicioReserva.reservaUsuario2(CapaGUI.ServicioReserva.reservaUsuario2Request request) {
            return base.Channel.reservaUsuario2(request);
        }
        
        public CapaGUI.ServicioReserva.reservaUsuario[] reservaUsuario2(string nombreUsuario) {
            CapaGUI.ServicioReserva.reservaUsuario2Request inValue = new CapaGUI.ServicioReserva.reservaUsuario2Request();
            inValue.nombreUsuario = nombreUsuario;
            CapaGUI.ServicioReserva.reservaUsuario2Response retVal = ((CapaGUI.ServicioReserva.ServicioReserva)(this)).reservaUsuario2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioReserva.reservaUsuario2Response> CapaGUI.ServicioReserva.ServicioReserva.reservaUsuario2Async(CapaGUI.ServicioReserva.reservaUsuario2Request request) {
            return base.Channel.reservaUsuario2Async(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioReserva.reservaUsuario2Response> reservaUsuario2Async(string nombreUsuario) {
            CapaGUI.ServicioReserva.reservaUsuario2Request inValue = new CapaGUI.ServicioReserva.reservaUsuario2Request();
            inValue.nombreUsuario = nombreUsuario;
            return ((CapaGUI.ServicioReserva.ServicioReserva)(this)).reservaUsuario2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioReserva.consultaReservasResponse CapaGUI.ServicioReserva.ServicioReserva.consultaReservas(CapaGUI.ServicioReserva.consultaReservasRequest request) {
            return base.Channel.consultaReservas(request);
        }
        
        public CapaGUI.ServicioReserva.reserva[] consultaReservas(string idDepto) {
            CapaGUI.ServicioReserva.consultaReservasRequest inValue = new CapaGUI.ServicioReserva.consultaReservasRequest();
            inValue.idDepto = idDepto;
            CapaGUI.ServicioReserva.consultaReservasResponse retVal = ((CapaGUI.ServicioReserva.ServicioReserva)(this)).consultaReservas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioReserva.consultaReservasResponse> CapaGUI.ServicioReserva.ServicioReserva.consultaReservasAsync(CapaGUI.ServicioReserva.consultaReservasRequest request) {
            return base.Channel.consultaReservasAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioReserva.consultaReservasResponse> consultaReservasAsync(string idDepto) {
            CapaGUI.ServicioReserva.consultaReservasRequest inValue = new CapaGUI.ServicioReserva.consultaReservasRequest();
            inValue.idDepto = idDepto;
            return ((CapaGUI.ServicioReserva.ServicioReserva)(this)).consultaReservasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioReserva.listarReservaResponse CapaGUI.ServicioReserva.ServicioReserva.listarReserva(CapaGUI.ServicioReserva.listarReservaRequest request) {
            return base.Channel.listarReserva(request);
        }
        
        public CapaGUI.ServicioReserva.reservaDto[] listarReserva() {
            CapaGUI.ServicioReserva.listarReservaRequest inValue = new CapaGUI.ServicioReserva.listarReservaRequest();
            CapaGUI.ServicioReserva.listarReservaResponse retVal = ((CapaGUI.ServicioReserva.ServicioReserva)(this)).listarReserva(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioReserva.listarReservaResponse> CapaGUI.ServicioReserva.ServicioReserva.listarReservaAsync(CapaGUI.ServicioReserva.listarReservaRequest request) {
            return base.Channel.listarReservaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioReserva.listarReservaResponse> listarReservaAsync() {
            CapaGUI.ServicioReserva.listarReservaRequest inValue = new CapaGUI.ServicioReserva.listarReservaRequest();
            return ((CapaGUI.ServicioReserva.ServicioReserva)(this)).listarReservaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioReserva.insertReservaResponse CapaGUI.ServicioReserva.ServicioReserva.insertReserva(CapaGUI.ServicioReserva.insertReservaRequest request) {
            return base.Channel.insertReserva(request);
        }
        
        public void insertReserva(string fechaInicio, string fechaFin, int pago, int idDpto, int idCliente) {
            CapaGUI.ServicioReserva.insertReservaRequest inValue = new CapaGUI.ServicioReserva.insertReservaRequest();
            inValue.fechaInicio = fechaInicio;
            inValue.fechaFin = fechaFin;
            inValue.pago = pago;
            inValue.idDpto = idDpto;
            inValue.idCliente = idCliente;
            CapaGUI.ServicioReserva.insertReservaResponse retVal = ((CapaGUI.ServicioReserva.ServicioReserva)(this)).insertReserva(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioReserva.insertReservaResponse> CapaGUI.ServicioReserva.ServicioReserva.insertReservaAsync(CapaGUI.ServicioReserva.insertReservaRequest request) {
            return base.Channel.insertReservaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioReserva.insertReservaResponse> insertReservaAsync(string fechaInicio, string fechaFin, int pago, int idDpto, int idCliente) {
            CapaGUI.ServicioReserva.insertReservaRequest inValue = new CapaGUI.ServicioReserva.insertReservaRequest();
            inValue.fechaInicio = fechaInicio;
            inValue.fechaFin = fechaFin;
            inValue.pago = pago;
            inValue.idDpto = idDpto;
            inValue.idCliente = idCliente;
            return ((CapaGUI.ServicioReserva.ServicioReserva)(this)).insertReservaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioReserva.GetTurismoByReservaResponse CapaGUI.ServicioReserva.ServicioReserva.GetTurismoByReserva(CapaGUI.ServicioReserva.GetTurismoByReservaRequest request) {
            return base.Channel.GetTurismoByReserva(request);
        }
        
        public CapaGUI.ServicioReserva.servicioReservaList[] GetTurismoByReserva(int idReserva) {
            CapaGUI.ServicioReserva.GetTurismoByReservaRequest inValue = new CapaGUI.ServicioReserva.GetTurismoByReservaRequest();
            inValue.idReserva = idReserva;
            CapaGUI.ServicioReserva.GetTurismoByReservaResponse retVal = ((CapaGUI.ServicioReserva.ServicioReserva)(this)).GetTurismoByReserva(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioReserva.GetTurismoByReservaResponse> CapaGUI.ServicioReserva.ServicioReserva.GetTurismoByReservaAsync(CapaGUI.ServicioReserva.GetTurismoByReservaRequest request) {
            return base.Channel.GetTurismoByReservaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioReserva.GetTurismoByReservaResponse> GetTurismoByReservaAsync(int idReserva) {
            CapaGUI.ServicioReserva.GetTurismoByReservaRequest inValue = new CapaGUI.ServicioReserva.GetTurismoByReservaRequest();
            inValue.idReserva = idReserva;
            return ((CapaGUI.ServicioReserva.ServicioReserva)(this)).GetTurismoByReservaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioReserva.consultaReservasOutResponse CapaGUI.ServicioReserva.ServicioReserva.consultaReservasOut(CapaGUI.ServicioReserva.consultaReservasOutRequest request) {
            return base.Channel.consultaReservasOut(request);
        }
        
        public CapaGUI.ServicioReserva.reserva[] consultaReservasOut() {
            CapaGUI.ServicioReserva.consultaReservasOutRequest inValue = new CapaGUI.ServicioReserva.consultaReservasOutRequest();
            CapaGUI.ServicioReserva.consultaReservasOutResponse retVal = ((CapaGUI.ServicioReserva.ServicioReserva)(this)).consultaReservasOut(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioReserva.consultaReservasOutResponse> CapaGUI.ServicioReserva.ServicioReserva.consultaReservasOutAsync(CapaGUI.ServicioReserva.consultaReservasOutRequest request) {
            return base.Channel.consultaReservasOutAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioReserva.consultaReservasOutResponse> consultaReservasOutAsync() {
            CapaGUI.ServicioReserva.consultaReservasOutRequest inValue = new CapaGUI.ServicioReserva.consultaReservasOutRequest();
            return ((CapaGUI.ServicioReserva.ServicioReserva)(this)).consultaReservasOutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioReserva.GetTransporteByReservaResponse CapaGUI.ServicioReserva.ServicioReserva.GetTransporteByReserva(CapaGUI.ServicioReserva.GetTransporteByReservaRequest request) {
            return base.Channel.GetTransporteByReserva(request);
        }
        
        public CapaGUI.ServicioReserva.servicioReservaList[] GetTransporteByReserva(int idReserva) {
            CapaGUI.ServicioReserva.GetTransporteByReservaRequest inValue = new CapaGUI.ServicioReserva.GetTransporteByReservaRequest();
            inValue.idReserva = idReserva;
            CapaGUI.ServicioReserva.GetTransporteByReservaResponse retVal = ((CapaGUI.ServicioReserva.ServicioReserva)(this)).GetTransporteByReserva(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioReserva.GetTransporteByReservaResponse> CapaGUI.ServicioReserva.ServicioReserva.GetTransporteByReservaAsync(CapaGUI.ServicioReserva.GetTransporteByReservaRequest request) {
            return base.Channel.GetTransporteByReservaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioReserva.GetTransporteByReservaResponse> GetTransporteByReservaAsync(int idReserva) {
            CapaGUI.ServicioReserva.GetTransporteByReservaRequest inValue = new CapaGUI.ServicioReserva.GetTransporteByReservaRequest();
            inValue.idReserva = idReserva;
            return ((CapaGUI.ServicioReserva.ServicioReserva)(this)).GetTransporteByReservaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioReserva.GetAcompaniantesByReservaResponse CapaGUI.ServicioReserva.ServicioReserva.GetAcompaniantesByReserva(CapaGUI.ServicioReserva.GetAcompaniantesByReservaRequest request) {
            return base.Channel.GetAcompaniantesByReserva(request);
        }
        
        public CapaGUI.ServicioReserva.acompanianteReserva[] GetAcompaniantesByReserva(int idReserva) {
            CapaGUI.ServicioReserva.GetAcompaniantesByReservaRequest inValue = new CapaGUI.ServicioReserva.GetAcompaniantesByReservaRequest();
            inValue.idReserva = idReserva;
            CapaGUI.ServicioReserva.GetAcompaniantesByReservaResponse retVal = ((CapaGUI.ServicioReserva.ServicioReserva)(this)).GetAcompaniantesByReserva(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioReserva.GetAcompaniantesByReservaResponse> CapaGUI.ServicioReserva.ServicioReserva.GetAcompaniantesByReservaAsync(CapaGUI.ServicioReserva.GetAcompaniantesByReservaRequest request) {
            return base.Channel.GetAcompaniantesByReservaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioReserva.GetAcompaniantesByReservaResponse> GetAcompaniantesByReservaAsync(int idReserva) {
            CapaGUI.ServicioReserva.GetAcompaniantesByReservaRequest inValue = new CapaGUI.ServicioReserva.GetAcompaniantesByReservaRequest();
            inValue.idReserva = idReserva;
            return ((CapaGUI.ServicioReserva.ServicioReserva)(this)).GetAcompaniantesByReservaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioReserva.validarFechaReservaResponse CapaGUI.ServicioReserva.ServicioReserva.validarFechaReserva(CapaGUI.ServicioReserva.validarFechaReservaRequest request) {
            return base.Channel.validarFechaReserva(request);
        }
        
        public string[] validarFechaReserva(int idDepto, string fecha_inicio, string fecha_fin) {
            CapaGUI.ServicioReserva.validarFechaReservaRequest inValue = new CapaGUI.ServicioReserva.validarFechaReservaRequest();
            inValue.idDepto = idDepto;
            inValue.fecha_inicio = fecha_inicio;
            inValue.fecha_fin = fecha_fin;
            CapaGUI.ServicioReserva.validarFechaReservaResponse retVal = ((CapaGUI.ServicioReserva.ServicioReserva)(this)).validarFechaReserva(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioReserva.validarFechaReservaResponse> CapaGUI.ServicioReserva.ServicioReserva.validarFechaReservaAsync(CapaGUI.ServicioReserva.validarFechaReservaRequest request) {
            return base.Channel.validarFechaReservaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioReserva.validarFechaReservaResponse> validarFechaReservaAsync(int idDepto, string fecha_inicio, string fecha_fin) {
            CapaGUI.ServicioReserva.validarFechaReservaRequest inValue = new CapaGUI.ServicioReserva.validarFechaReservaRequest();
            inValue.idDepto = idDepto;
            inValue.fecha_inicio = fecha_inicio;
            inValue.fecha_fin = fecha_fin;
            return ((CapaGUI.ServicioReserva.ServicioReserva)(this)).validarFechaReservaAsync(inValue);
        }
    }
}
