//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServicioTurismo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Servicios/", ConfigurationName="ServicioTurismo.ServicioTurismo")]
    public interface ServicioTurismo {
        
        // CODEGEN: El parámetro 'v_ID_TURISMO' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioTurismo/ActualizarTurismoRequest", ReplyAction="http://Servicios/ServicioTurismo/ActualizarTurismoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUI.ServicioTurismo.ActualizarTurismoResponse ActualizarTurismo(CapaGUI.ServicioTurismo.ActualizarTurismoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioTurismo/ActualizarTurismoRequest", ReplyAction="http://Servicios/ServicioTurismo/ActualizarTurismoResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioTurismo.ActualizarTurismoResponse> ActualizarTurismoAsync(CapaGUI.ServicioTurismo.ActualizarTurismoRequest request);
        
        // CODEGEN: El parámetro 'idTurismo' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioTurismo/eliminarTurismoRequest", ReplyAction="http://Servicios/ServicioTurismo/eliminarTurismoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUI.ServicioTurismo.eliminarTurismoResponse eliminarTurismo(CapaGUI.ServicioTurismo.eliminarTurismoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioTurismo/eliminarTurismoRequest", ReplyAction="http://Servicios/ServicioTurismo/eliminarTurismoResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioTurismo.eliminarTurismoResponse> eliminarTurismoAsync(CapaGUI.ServicioTurismo.eliminarTurismoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioTurismo/listarTurismoRequest", ReplyAction="http://Servicios/ServicioTurismo/listarTurismoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaGUI.ServicioTurismo.listarTurismoResponse listarTurismo(CapaGUI.ServicioTurismo.listarTurismoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioTurismo/listarTurismoRequest", ReplyAction="http://Servicios/ServicioTurismo/listarTurismoResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioTurismo.listarTurismoResponse> listarTurismoAsync(CapaGUI.ServicioTurismo.listarTurismoRequest request);
        
        // CODEGEN: El parámetro 'Descripcion' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioTurismo/IngresarTurismoRequest", ReplyAction="http://Servicios/ServicioTurismo/IngresarTurismoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CapaGUI.ServicioTurismo.IngresarTurismoResponse IngresarTurismo(CapaGUI.ServicioTurismo.IngresarTurismoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioTurismo/IngresarTurismoRequest", ReplyAction="http://Servicios/ServicioTurismo/IngresarTurismoResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioTurismo.IngresarTurismoResponse> IngresarTurismoAsync(CapaGUI.ServicioTurismo.IngresarTurismoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarTurismo", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class ActualizarTurismoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int v_ID_TURISMO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string v_DESCRIPCION;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int v_PRECIO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int v_ID_DISPONIBILIDAD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string V_FECHA;
        
        public ActualizarTurismoRequest() {
        }
        
        public ActualizarTurismoRequest(int v_ID_TURISMO, string v_DESCRIPCION, int v_PRECIO, int v_ID_DISPONIBILIDAD, string V_FECHA) {
            this.v_ID_TURISMO = v_ID_TURISMO;
            this.v_DESCRIPCION = v_DESCRIPCION;
            this.v_PRECIO = v_PRECIO;
            this.v_ID_DISPONIBILIDAD = v_ID_DISPONIBILIDAD;
            this.V_FECHA = V_FECHA;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActualizarTurismoResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class ActualizarTurismoResponse {
        
        public ActualizarTurismoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarTurismo", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class eliminarTurismoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTurismo;
        
        public eliminarTurismoRequest() {
        }
        
        public eliminarTurismoRequest(int idTurismo) {
            this.idTurismo = idTurismo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarTurismoResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class eliminarTurismoResponse {
        
        public eliminarTurismoResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class listaTurismo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private string disponibilidadField;
        
        private string fechaField;
        
        private int idTurismoField;
        
        private int precioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string disponibilidad {
            get {
                return this.disponibilidadField;
            }
            set {
                this.disponibilidadField = value;
                this.RaisePropertyChanged("disponibilidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idTurismo {
            get {
                return this.idTurismoField;
            }
            set {
                this.idTurismoField = value;
                this.RaisePropertyChanged("idTurismo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTurismo", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class listarTurismoRequest {
        
        public listarTurismoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTurismoResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class listarTurismoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CapaGUI.ServicioTurismo.listaTurismo[] @return;
        
        public listarTurismoResponse() {
        }
        
        public listarTurismoResponse(CapaGUI.ServicioTurismo.listaTurismo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IngresarTurismo", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class IngresarTurismoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Precio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Disponibilidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string V_FECHA;
        
        public IngresarTurismoRequest() {
        }
        
        public IngresarTurismoRequest(string Descripcion, int Precio, int Disponibilidad, string V_FECHA) {
            this.Descripcion = Descripcion;
            this.Precio = Precio;
            this.Disponibilidad = Disponibilidad;
            this.V_FECHA = V_FECHA;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IngresarTurismoResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class IngresarTurismoResponse {
        
        public IngresarTurismoResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioTurismoChannel : CapaGUI.ServicioTurismo.ServicioTurismo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioTurismoClient : System.ServiceModel.ClientBase<CapaGUI.ServicioTurismo.ServicioTurismo>, CapaGUI.ServicioTurismo.ServicioTurismo {
        
        public ServicioTurismoClient() {
        }
        
        public ServicioTurismoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioTurismoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioTurismoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioTurismoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioTurismo.ActualizarTurismoResponse CapaGUI.ServicioTurismo.ServicioTurismo.ActualizarTurismo(CapaGUI.ServicioTurismo.ActualizarTurismoRequest request) {
            return base.Channel.ActualizarTurismo(request);
        }
        
        public void ActualizarTurismo(int v_ID_TURISMO, string v_DESCRIPCION, int v_PRECIO, int v_ID_DISPONIBILIDAD, string V_FECHA) {
            CapaGUI.ServicioTurismo.ActualizarTurismoRequest inValue = new CapaGUI.ServicioTurismo.ActualizarTurismoRequest();
            inValue.v_ID_TURISMO = v_ID_TURISMO;
            inValue.v_DESCRIPCION = v_DESCRIPCION;
            inValue.v_PRECIO = v_PRECIO;
            inValue.v_ID_DISPONIBILIDAD = v_ID_DISPONIBILIDAD;
            inValue.V_FECHA = V_FECHA;
            CapaGUI.ServicioTurismo.ActualizarTurismoResponse retVal = ((CapaGUI.ServicioTurismo.ServicioTurismo)(this)).ActualizarTurismo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioTurismo.ActualizarTurismoResponse> CapaGUI.ServicioTurismo.ServicioTurismo.ActualizarTurismoAsync(CapaGUI.ServicioTurismo.ActualizarTurismoRequest request) {
            return base.Channel.ActualizarTurismoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioTurismo.ActualizarTurismoResponse> ActualizarTurismoAsync(int v_ID_TURISMO, string v_DESCRIPCION, int v_PRECIO, int v_ID_DISPONIBILIDAD, string V_FECHA) {
            CapaGUI.ServicioTurismo.ActualizarTurismoRequest inValue = new CapaGUI.ServicioTurismo.ActualizarTurismoRequest();
            inValue.v_ID_TURISMO = v_ID_TURISMO;
            inValue.v_DESCRIPCION = v_DESCRIPCION;
            inValue.v_PRECIO = v_PRECIO;
            inValue.v_ID_DISPONIBILIDAD = v_ID_DISPONIBILIDAD;
            inValue.V_FECHA = V_FECHA;
            return ((CapaGUI.ServicioTurismo.ServicioTurismo)(this)).ActualizarTurismoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioTurismo.eliminarTurismoResponse CapaGUI.ServicioTurismo.ServicioTurismo.eliminarTurismo(CapaGUI.ServicioTurismo.eliminarTurismoRequest request) {
            return base.Channel.eliminarTurismo(request);
        }
        
        public void eliminarTurismo(int idTurismo) {
            CapaGUI.ServicioTurismo.eliminarTurismoRequest inValue = new CapaGUI.ServicioTurismo.eliminarTurismoRequest();
            inValue.idTurismo = idTurismo;
            CapaGUI.ServicioTurismo.eliminarTurismoResponse retVal = ((CapaGUI.ServicioTurismo.ServicioTurismo)(this)).eliminarTurismo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioTurismo.eliminarTurismoResponse> CapaGUI.ServicioTurismo.ServicioTurismo.eliminarTurismoAsync(CapaGUI.ServicioTurismo.eliminarTurismoRequest request) {
            return base.Channel.eliminarTurismoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioTurismo.eliminarTurismoResponse> eliminarTurismoAsync(int idTurismo) {
            CapaGUI.ServicioTurismo.eliminarTurismoRequest inValue = new CapaGUI.ServicioTurismo.eliminarTurismoRequest();
            inValue.idTurismo = idTurismo;
            return ((CapaGUI.ServicioTurismo.ServicioTurismo)(this)).eliminarTurismoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioTurismo.listarTurismoResponse CapaGUI.ServicioTurismo.ServicioTurismo.listarTurismo(CapaGUI.ServicioTurismo.listarTurismoRequest request) {
            return base.Channel.listarTurismo(request);
        }
        
        public CapaGUI.ServicioTurismo.listaTurismo[] listarTurismo() {
            CapaGUI.ServicioTurismo.listarTurismoRequest inValue = new CapaGUI.ServicioTurismo.listarTurismoRequest();
            CapaGUI.ServicioTurismo.listarTurismoResponse retVal = ((CapaGUI.ServicioTurismo.ServicioTurismo)(this)).listarTurismo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioTurismo.listarTurismoResponse> CapaGUI.ServicioTurismo.ServicioTurismo.listarTurismoAsync(CapaGUI.ServicioTurismo.listarTurismoRequest request) {
            return base.Channel.listarTurismoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioTurismo.listarTurismoResponse> listarTurismoAsync() {
            CapaGUI.ServicioTurismo.listarTurismoRequest inValue = new CapaGUI.ServicioTurismo.listarTurismoRequest();
            return ((CapaGUI.ServicioTurismo.ServicioTurismo)(this)).listarTurismoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioTurismo.IngresarTurismoResponse CapaGUI.ServicioTurismo.ServicioTurismo.IngresarTurismo(CapaGUI.ServicioTurismo.IngresarTurismoRequest request) {
            return base.Channel.IngresarTurismo(request);
        }
        
        public void IngresarTurismo(string Descripcion, int Precio, int Disponibilidad, string V_FECHA) {
            CapaGUI.ServicioTurismo.IngresarTurismoRequest inValue = new CapaGUI.ServicioTurismo.IngresarTurismoRequest();
            inValue.Descripcion = Descripcion;
            inValue.Precio = Precio;
            inValue.Disponibilidad = Disponibilidad;
            inValue.V_FECHA = V_FECHA;
            CapaGUI.ServicioTurismo.IngresarTurismoResponse retVal = ((CapaGUI.ServicioTurismo.ServicioTurismo)(this)).IngresarTurismo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioTurismo.IngresarTurismoResponse> CapaGUI.ServicioTurismo.ServicioTurismo.IngresarTurismoAsync(CapaGUI.ServicioTurismo.IngresarTurismoRequest request) {
            return base.Channel.IngresarTurismoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioTurismo.IngresarTurismoResponse> IngresarTurismoAsync(string Descripcion, int Precio, int Disponibilidad, string V_FECHA) {
            CapaGUI.ServicioTurismo.IngresarTurismoRequest inValue = new CapaGUI.ServicioTurismo.IngresarTurismoRequest();
            inValue.Descripcion = Descripcion;
            inValue.Precio = Precio;
            inValue.Disponibilidad = Disponibilidad;
            inValue.V_FECHA = V_FECHA;
            return ((CapaGUI.ServicioTurismo.ServicioTurismo)(this)).IngresarTurismoAsync(inValue);
        }
    }
}
