//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServicioCheckOut {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Servicios/", ConfigurationName="ServicioCheckOut.ServicioCheckOut")]
    public interface ServicioCheckOut {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento V_DESCRIPCION del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioCheckOut/insertarDetalleMultaRequest", ReplyAction="http://Servicios/ServicioCheckOut/insertarDetalleMultaResponse")]
        CapaGUI.ServicioCheckOut.insertarDetalleMultaResponse insertarDetalleMulta(CapaGUI.ServicioCheckOut.insertarDetalleMultaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioCheckOut/insertarDetalleMultaRequest", ReplyAction="http://Servicios/ServicioCheckOut/insertarDetalleMultaResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioCheckOut.insertarDetalleMultaResponse> insertarDetalleMultaAsync(CapaGUI.ServicioCheckOut.insertarDetalleMultaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento V_FECHA del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioCheckOut/insertarCheckOutMultaRequest", ReplyAction="http://Servicios/ServicioCheckOut/insertarCheckOutMultaResponse")]
        CapaGUI.ServicioCheckOut.insertarCheckOutMultaResponse insertarCheckOutMulta(CapaGUI.ServicioCheckOut.insertarCheckOutMultaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioCheckOut/insertarCheckOutMultaRequest", ReplyAction="http://Servicios/ServicioCheckOut/insertarCheckOutMultaResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioCheckOut.insertarCheckOutMultaResponse> insertarCheckOutMultaAsync(CapaGUI.ServicioCheckOut.insertarCheckOutMultaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento V_FECHA del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioCheckOut/insertarCheckOutMulta2Request", ReplyAction="http://Servicios/ServicioCheckOut/insertarCheckOutMulta2Response")]
        CapaGUI.ServicioCheckOut.insertarCheckOutMulta2Response insertarCheckOutMulta2(CapaGUI.ServicioCheckOut.insertarCheckOutMulta2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioCheckOut/insertarCheckOutMulta2Request", ReplyAction="http://Servicios/ServicioCheckOut/insertarCheckOutMulta2Response")]
        System.Threading.Tasks.Task<CapaGUI.ServicioCheckOut.insertarCheckOutMulta2Response> insertarCheckOutMulta2Async(CapaGUI.ServicioCheckOut.insertarCheckOutMulta2Request request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Fecha del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioCheckOut/insertarCheckOutRequest", ReplyAction="http://Servicios/ServicioCheckOut/insertarCheckOutResponse")]
        CapaGUI.ServicioCheckOut.insertarCheckOutResponse insertarCheckOut(CapaGUI.ServicioCheckOut.insertarCheckOutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioCheckOut/insertarCheckOutRequest", ReplyAction="http://Servicios/ServicioCheckOut/insertarCheckOutResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioCheckOut.insertarCheckOutResponse> insertarCheckOutAsync(CapaGUI.ServicioCheckOut.insertarCheckOutRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://Servicios/).
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioCheckOut/getLastIDRequest", ReplyAction="http://Servicios/ServicioCheckOut/getLastIDResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CapaGUI.ServicioCheckOut.getLastIDResponse getLastID(CapaGUI.ServicioCheckOut.getLastIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioCheckOut/getLastIDRequest", ReplyAction="http://Servicios/ServicioCheckOut/getLastIDResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioCheckOut.getLastIDResponse> getLastIDAsync(CapaGUI.ServicioCheckOut.getLastIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarDetalleMultaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarDetalleMulta", Namespace="http://Servicios/", Order=0)]
        public CapaGUI.ServicioCheckOut.insertarDetalleMultaRequestBody Body;
        
        public insertarDetalleMultaRequest() {
        }
        
        public insertarDetalleMultaRequest(CapaGUI.ServicioCheckOut.insertarDetalleMultaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class insertarDetalleMultaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int V_TOTAL_MULTA;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string V_DESCRIPCION;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int V_ID_MAXMULTA;
        
        public insertarDetalleMultaRequestBody() {
        }
        
        public insertarDetalleMultaRequestBody(int V_TOTAL_MULTA, string V_DESCRIPCION, int V_ID_MAXMULTA) {
            this.V_TOTAL_MULTA = V_TOTAL_MULTA;
            this.V_DESCRIPCION = V_DESCRIPCION;
            this.V_ID_MAXMULTA = V_ID_MAXMULTA;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarDetalleMultaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarDetalleMultaResponse", Namespace="http://Servicios/", Order=0)]
        public CapaGUI.ServicioCheckOut.insertarDetalleMultaResponseBody Body;
        
        public insertarDetalleMultaResponse() {
        }
        
        public insertarDetalleMultaResponse(CapaGUI.ServicioCheckOut.insertarDetalleMultaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class insertarDetalleMultaResponseBody {
        
        public insertarDetalleMultaResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarCheckOutMultaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarCheckOutMulta", Namespace="http://Servicios/", Order=0)]
        public CapaGUI.ServicioCheckOut.insertarCheckOutMultaRequestBody Body;
        
        public insertarCheckOutMultaRequest() {
        }
        
        public insertarCheckOutMultaRequest(CapaGUI.ServicioCheckOut.insertarCheckOutMultaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class insertarCheckOutMultaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int V_TOTAL_MULTA;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int V_ID_CHECK_OUT;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int V_ID_CHECK_IN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string V_FECHA;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int V_ID_RECURSOS;
        
        public insertarCheckOutMultaRequestBody() {
        }
        
        public insertarCheckOutMultaRequestBody(int V_TOTAL_MULTA, int V_ID_CHECK_OUT, int V_ID_CHECK_IN, string V_FECHA, int V_ID_RECURSOS) {
            this.V_TOTAL_MULTA = V_TOTAL_MULTA;
            this.V_ID_CHECK_OUT = V_ID_CHECK_OUT;
            this.V_ID_CHECK_IN = V_ID_CHECK_IN;
            this.V_FECHA = V_FECHA;
            this.V_ID_RECURSOS = V_ID_RECURSOS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarCheckOutMultaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarCheckOutMultaResponse", Namespace="http://Servicios/", Order=0)]
        public CapaGUI.ServicioCheckOut.insertarCheckOutMultaResponseBody Body;
        
        public insertarCheckOutMultaResponse() {
        }
        
        public insertarCheckOutMultaResponse(CapaGUI.ServicioCheckOut.insertarCheckOutMultaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class insertarCheckOutMultaResponseBody {
        
        public insertarCheckOutMultaResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarCheckOutMulta2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarCheckOutMulta2", Namespace="http://Servicios/", Order=0)]
        public CapaGUI.ServicioCheckOut.insertarCheckOutMulta2RequestBody Body;
        
        public insertarCheckOutMulta2Request() {
        }
        
        public insertarCheckOutMulta2Request(CapaGUI.ServicioCheckOut.insertarCheckOutMulta2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class insertarCheckOutMulta2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int V_TOTAL_MULTA;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int V_ID_CHECK_OUT;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int V_ID_CHECK_IN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string V_FECHA;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int V_ID_RECURSOS;
        
        public insertarCheckOutMulta2RequestBody() {
        }
        
        public insertarCheckOutMulta2RequestBody(int V_TOTAL_MULTA, int V_ID_CHECK_OUT, int V_ID_CHECK_IN, string V_FECHA, int V_ID_RECURSOS) {
            this.V_TOTAL_MULTA = V_TOTAL_MULTA;
            this.V_ID_CHECK_OUT = V_ID_CHECK_OUT;
            this.V_ID_CHECK_IN = V_ID_CHECK_IN;
            this.V_FECHA = V_FECHA;
            this.V_ID_RECURSOS = V_ID_RECURSOS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarCheckOutMulta2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarCheckOutMulta2Response", Namespace="http://Servicios/", Order=0)]
        public CapaGUI.ServicioCheckOut.insertarCheckOutMulta2ResponseBody Body;
        
        public insertarCheckOutMulta2Response() {
        }
        
        public insertarCheckOutMulta2Response(CapaGUI.ServicioCheckOut.insertarCheckOutMulta2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class insertarCheckOutMulta2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public insertarCheckOutMulta2ResponseBody() {
        }
        
        public insertarCheckOutMulta2ResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarCheckOutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarCheckOut", Namespace="http://Servicios/", Order=0)]
        public CapaGUI.ServicioCheckOut.insertarCheckOutRequestBody Body;
        
        public insertarCheckOutRequest() {
        }
        
        public insertarCheckOutRequest(CapaGUI.ServicioCheckOut.insertarCheckOutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class insertarCheckOutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idCheckIn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Fecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int idRecursoHumano;
        
        public insertarCheckOutRequestBody() {
        }
        
        public insertarCheckOutRequestBody(int idCheckIn, string Fecha, int idRecursoHumano) {
            this.idCheckIn = idCheckIn;
            this.Fecha = Fecha;
            this.idRecursoHumano = idRecursoHumano;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarCheckOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarCheckOutResponse", Namespace="http://Servicios/", Order=0)]
        public CapaGUI.ServicioCheckOut.insertarCheckOutResponseBody Body;
        
        public insertarCheckOutResponse() {
        }
        
        public insertarCheckOutResponse(CapaGUI.ServicioCheckOut.insertarCheckOutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class insertarCheckOutResponseBody {
        
        public insertarCheckOutResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLastID", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class getLastIDRequest {
        
        public getLastIDRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLastIDResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class getLastIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public getLastIDResponse() {
        }
        
        public getLastIDResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioCheckOutChannel : CapaGUI.ServicioCheckOut.ServicioCheckOut, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioCheckOutClient : System.ServiceModel.ClientBase<CapaGUI.ServicioCheckOut.ServicioCheckOut>, CapaGUI.ServicioCheckOut.ServicioCheckOut {
        
        public ServicioCheckOutClient() {
        }
        
        public ServicioCheckOutClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioCheckOutClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCheckOutClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCheckOutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioCheckOut.insertarDetalleMultaResponse CapaGUI.ServicioCheckOut.ServicioCheckOut.insertarDetalleMulta(CapaGUI.ServicioCheckOut.insertarDetalleMultaRequest request) {
            return base.Channel.insertarDetalleMulta(request);
        }
        
        public void insertarDetalleMulta(int V_TOTAL_MULTA, string V_DESCRIPCION, int V_ID_MAXMULTA) {
            CapaGUI.ServicioCheckOut.insertarDetalleMultaRequest inValue = new CapaGUI.ServicioCheckOut.insertarDetalleMultaRequest();
            inValue.Body = new CapaGUI.ServicioCheckOut.insertarDetalleMultaRequestBody();
            inValue.Body.V_TOTAL_MULTA = V_TOTAL_MULTA;
            inValue.Body.V_DESCRIPCION = V_DESCRIPCION;
            inValue.Body.V_ID_MAXMULTA = V_ID_MAXMULTA;
            CapaGUI.ServicioCheckOut.insertarDetalleMultaResponse retVal = ((CapaGUI.ServicioCheckOut.ServicioCheckOut)(this)).insertarDetalleMulta(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioCheckOut.insertarDetalleMultaResponse> CapaGUI.ServicioCheckOut.ServicioCheckOut.insertarDetalleMultaAsync(CapaGUI.ServicioCheckOut.insertarDetalleMultaRequest request) {
            return base.Channel.insertarDetalleMultaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioCheckOut.insertarDetalleMultaResponse> insertarDetalleMultaAsync(int V_TOTAL_MULTA, string V_DESCRIPCION, int V_ID_MAXMULTA) {
            CapaGUI.ServicioCheckOut.insertarDetalleMultaRequest inValue = new CapaGUI.ServicioCheckOut.insertarDetalleMultaRequest();
            inValue.Body = new CapaGUI.ServicioCheckOut.insertarDetalleMultaRequestBody();
            inValue.Body.V_TOTAL_MULTA = V_TOTAL_MULTA;
            inValue.Body.V_DESCRIPCION = V_DESCRIPCION;
            inValue.Body.V_ID_MAXMULTA = V_ID_MAXMULTA;
            return ((CapaGUI.ServicioCheckOut.ServicioCheckOut)(this)).insertarDetalleMultaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioCheckOut.insertarCheckOutMultaResponse CapaGUI.ServicioCheckOut.ServicioCheckOut.insertarCheckOutMulta(CapaGUI.ServicioCheckOut.insertarCheckOutMultaRequest request) {
            return base.Channel.insertarCheckOutMulta(request);
        }
        
        public void insertarCheckOutMulta(int V_TOTAL_MULTA, int V_ID_CHECK_OUT, int V_ID_CHECK_IN, string V_FECHA, int V_ID_RECURSOS) {
            CapaGUI.ServicioCheckOut.insertarCheckOutMultaRequest inValue = new CapaGUI.ServicioCheckOut.insertarCheckOutMultaRequest();
            inValue.Body = new CapaGUI.ServicioCheckOut.insertarCheckOutMultaRequestBody();
            inValue.Body.V_TOTAL_MULTA = V_TOTAL_MULTA;
            inValue.Body.V_ID_CHECK_OUT = V_ID_CHECK_OUT;
            inValue.Body.V_ID_CHECK_IN = V_ID_CHECK_IN;
            inValue.Body.V_FECHA = V_FECHA;
            inValue.Body.V_ID_RECURSOS = V_ID_RECURSOS;
            CapaGUI.ServicioCheckOut.insertarCheckOutMultaResponse retVal = ((CapaGUI.ServicioCheckOut.ServicioCheckOut)(this)).insertarCheckOutMulta(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioCheckOut.insertarCheckOutMultaResponse> CapaGUI.ServicioCheckOut.ServicioCheckOut.insertarCheckOutMultaAsync(CapaGUI.ServicioCheckOut.insertarCheckOutMultaRequest request) {
            return base.Channel.insertarCheckOutMultaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioCheckOut.insertarCheckOutMultaResponse> insertarCheckOutMultaAsync(int V_TOTAL_MULTA, int V_ID_CHECK_OUT, int V_ID_CHECK_IN, string V_FECHA, int V_ID_RECURSOS) {
            CapaGUI.ServicioCheckOut.insertarCheckOutMultaRequest inValue = new CapaGUI.ServicioCheckOut.insertarCheckOutMultaRequest();
            inValue.Body = new CapaGUI.ServicioCheckOut.insertarCheckOutMultaRequestBody();
            inValue.Body.V_TOTAL_MULTA = V_TOTAL_MULTA;
            inValue.Body.V_ID_CHECK_OUT = V_ID_CHECK_OUT;
            inValue.Body.V_ID_CHECK_IN = V_ID_CHECK_IN;
            inValue.Body.V_FECHA = V_FECHA;
            inValue.Body.V_ID_RECURSOS = V_ID_RECURSOS;
            return ((CapaGUI.ServicioCheckOut.ServicioCheckOut)(this)).insertarCheckOutMultaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioCheckOut.insertarCheckOutMulta2Response CapaGUI.ServicioCheckOut.ServicioCheckOut.insertarCheckOutMulta2(CapaGUI.ServicioCheckOut.insertarCheckOutMulta2Request request) {
            return base.Channel.insertarCheckOutMulta2(request);
        }
        
        public int insertarCheckOutMulta2(int V_TOTAL_MULTA, int V_ID_CHECK_OUT, int V_ID_CHECK_IN, string V_FECHA, int V_ID_RECURSOS) {
            CapaGUI.ServicioCheckOut.insertarCheckOutMulta2Request inValue = new CapaGUI.ServicioCheckOut.insertarCheckOutMulta2Request();
            inValue.Body = new CapaGUI.ServicioCheckOut.insertarCheckOutMulta2RequestBody();
            inValue.Body.V_TOTAL_MULTA = V_TOTAL_MULTA;
            inValue.Body.V_ID_CHECK_OUT = V_ID_CHECK_OUT;
            inValue.Body.V_ID_CHECK_IN = V_ID_CHECK_IN;
            inValue.Body.V_FECHA = V_FECHA;
            inValue.Body.V_ID_RECURSOS = V_ID_RECURSOS;
            CapaGUI.ServicioCheckOut.insertarCheckOutMulta2Response retVal = ((CapaGUI.ServicioCheckOut.ServicioCheckOut)(this)).insertarCheckOutMulta2(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioCheckOut.insertarCheckOutMulta2Response> CapaGUI.ServicioCheckOut.ServicioCheckOut.insertarCheckOutMulta2Async(CapaGUI.ServicioCheckOut.insertarCheckOutMulta2Request request) {
            return base.Channel.insertarCheckOutMulta2Async(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioCheckOut.insertarCheckOutMulta2Response> insertarCheckOutMulta2Async(int V_TOTAL_MULTA, int V_ID_CHECK_OUT, int V_ID_CHECK_IN, string V_FECHA, int V_ID_RECURSOS) {
            CapaGUI.ServicioCheckOut.insertarCheckOutMulta2Request inValue = new CapaGUI.ServicioCheckOut.insertarCheckOutMulta2Request();
            inValue.Body = new CapaGUI.ServicioCheckOut.insertarCheckOutMulta2RequestBody();
            inValue.Body.V_TOTAL_MULTA = V_TOTAL_MULTA;
            inValue.Body.V_ID_CHECK_OUT = V_ID_CHECK_OUT;
            inValue.Body.V_ID_CHECK_IN = V_ID_CHECK_IN;
            inValue.Body.V_FECHA = V_FECHA;
            inValue.Body.V_ID_RECURSOS = V_ID_RECURSOS;
            return ((CapaGUI.ServicioCheckOut.ServicioCheckOut)(this)).insertarCheckOutMulta2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioCheckOut.insertarCheckOutResponse CapaGUI.ServicioCheckOut.ServicioCheckOut.insertarCheckOut(CapaGUI.ServicioCheckOut.insertarCheckOutRequest request) {
            return base.Channel.insertarCheckOut(request);
        }
        
        public void insertarCheckOut(int idCheckIn, string Fecha, int idRecursoHumano) {
            CapaGUI.ServicioCheckOut.insertarCheckOutRequest inValue = new CapaGUI.ServicioCheckOut.insertarCheckOutRequest();
            inValue.Body = new CapaGUI.ServicioCheckOut.insertarCheckOutRequestBody();
            inValue.Body.idCheckIn = idCheckIn;
            inValue.Body.Fecha = Fecha;
            inValue.Body.idRecursoHumano = idRecursoHumano;
            CapaGUI.ServicioCheckOut.insertarCheckOutResponse retVal = ((CapaGUI.ServicioCheckOut.ServicioCheckOut)(this)).insertarCheckOut(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioCheckOut.insertarCheckOutResponse> CapaGUI.ServicioCheckOut.ServicioCheckOut.insertarCheckOutAsync(CapaGUI.ServicioCheckOut.insertarCheckOutRequest request) {
            return base.Channel.insertarCheckOutAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioCheckOut.insertarCheckOutResponse> insertarCheckOutAsync(int idCheckIn, string Fecha, int idRecursoHumano) {
            CapaGUI.ServicioCheckOut.insertarCheckOutRequest inValue = new CapaGUI.ServicioCheckOut.insertarCheckOutRequest();
            inValue.Body = new CapaGUI.ServicioCheckOut.insertarCheckOutRequestBody();
            inValue.Body.idCheckIn = idCheckIn;
            inValue.Body.Fecha = Fecha;
            inValue.Body.idRecursoHumano = idRecursoHumano;
            return ((CapaGUI.ServicioCheckOut.ServicioCheckOut)(this)).insertarCheckOutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioCheckOut.getLastIDResponse CapaGUI.ServicioCheckOut.ServicioCheckOut.getLastID(CapaGUI.ServicioCheckOut.getLastIDRequest request) {
            return base.Channel.getLastID(request);
        }
        
        public int getLastID() {
            CapaGUI.ServicioCheckOut.getLastIDRequest inValue = new CapaGUI.ServicioCheckOut.getLastIDRequest();
            CapaGUI.ServicioCheckOut.getLastIDResponse retVal = ((CapaGUI.ServicioCheckOut.ServicioCheckOut)(this)).getLastID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioCheckOut.getLastIDResponse> CapaGUI.ServicioCheckOut.ServicioCheckOut.getLastIDAsync(CapaGUI.ServicioCheckOut.getLastIDRequest request) {
            return base.Channel.getLastIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioCheckOut.getLastIDResponse> getLastIDAsync() {
            CapaGUI.ServicioCheckOut.getLastIDRequest inValue = new CapaGUI.ServicioCheckOut.getLastIDRequest();
            return ((CapaGUI.ServicioCheckOut.ServicioCheckOut)(this)).getLastIDAsync(inValue);
        }
    }
}
