//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServicioCalculo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Servicios/", ConfigurationName="ServicioCalculo.ServicioCalculoPago")]
    public interface ServicioCalculoPago {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fecha_ini del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioCalculoPago/calculoPagoRequest", ReplyAction="http://Servicios/ServicioCalculoPago/calculoPagoResponse")]
        CapaGUI.ServicioCalculo.calculoPagoResponse calculoPago(CapaGUI.ServicioCalculo.calculoPagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/ServicioCalculoPago/calculoPagoRequest", ReplyAction="http://Servicios/ServicioCalculoPago/calculoPagoResponse")]
        System.Threading.Tasks.Task<CapaGUI.ServicioCalculo.calculoPagoResponse> calculoPagoAsync(CapaGUI.ServicioCalculo.calculoPagoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class calculoPagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="calculoPago", Namespace="http://Servicios/", Order=0)]
        public CapaGUI.ServicioCalculo.calculoPagoRequestBody Body;
        
        public calculoPagoRequest() {
        }
        
        public calculoPagoRequest(CapaGUI.ServicioCalculo.calculoPagoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class calculoPagoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idDepto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fecha_ini;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fecha_fin;
        
        public calculoPagoRequestBody() {
        }
        
        public calculoPagoRequestBody(int idDepto, string fecha_ini, string fecha_fin) {
            this.idDepto = idDepto;
            this.fecha_ini = fecha_ini;
            this.fecha_fin = fecha_fin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class calculoPagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="calculoPagoResponse", Namespace="http://Servicios/", Order=0)]
        public CapaGUI.ServicioCalculo.calculoPagoResponseBody Body;
        
        public calculoPagoResponse() {
        }
        
        public calculoPagoResponse(CapaGUI.ServicioCalculo.calculoPagoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class calculoPagoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public calculoPagoResponseBody() {
        }
        
        public calculoPagoResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioCalculoPagoChannel : CapaGUI.ServicioCalculo.ServicioCalculoPago, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioCalculoPagoClient : System.ServiceModel.ClientBase<CapaGUI.ServicioCalculo.ServicioCalculoPago>, CapaGUI.ServicioCalculo.ServicioCalculoPago {
        
        public ServicioCalculoPagoClient() {
        }
        
        public ServicioCalculoPagoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioCalculoPagoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCalculoPagoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCalculoPagoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CapaGUI.ServicioCalculo.calculoPagoResponse CapaGUI.ServicioCalculo.ServicioCalculoPago.calculoPago(CapaGUI.ServicioCalculo.calculoPagoRequest request) {
            return base.Channel.calculoPago(request);
        }
        
        public int calculoPago(int idDepto, string fecha_ini, string fecha_fin) {
            CapaGUI.ServicioCalculo.calculoPagoRequest inValue = new CapaGUI.ServicioCalculo.calculoPagoRequest();
            inValue.Body = new CapaGUI.ServicioCalculo.calculoPagoRequestBody();
            inValue.Body.idDepto = idDepto;
            inValue.Body.fecha_ini = fecha_ini;
            inValue.Body.fecha_fin = fecha_fin;
            CapaGUI.ServicioCalculo.calculoPagoResponse retVal = ((CapaGUI.ServicioCalculo.ServicioCalculoPago)(this)).calculoPago(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CapaGUI.ServicioCalculo.calculoPagoResponse> CapaGUI.ServicioCalculo.ServicioCalculoPago.calculoPagoAsync(CapaGUI.ServicioCalculo.calculoPagoRequest request) {
            return base.Channel.calculoPagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CapaGUI.ServicioCalculo.calculoPagoResponse> calculoPagoAsync(int idDepto, string fecha_ini, string fecha_fin) {
            CapaGUI.ServicioCalculo.calculoPagoRequest inValue = new CapaGUI.ServicioCalculo.calculoPagoRequest();
            inValue.Body = new CapaGUI.ServicioCalculo.calculoPagoRequestBody();
            inValue.Body.idDepto = idDepto;
            inValue.Body.fecha_ini = fecha_ini;
            inValue.Body.fecha_fin = fecha_fin;
            return ((CapaGUI.ServicioCalculo.ServicioCalculoPago)(this)).calculoPagoAsync(inValue);
        }
    }
}
